import Link from 'next/link';

export const metadata = { title: 'Terms of Service — Protocol' };

export default function TermsPage() {
  return (
    <div className="max-w-2xl mx-auto px-6 py-12 space-y-6">
      <Link href="/" className="text-accent font-bold text-lg">Protocol</Link>
      <h1 className="text-3xl font-bold">Terms of Service</h1>
      <p className="text-sm text-muted-foreground">Last updated: April 2026</p>

      <section className="space-y-3 rounded-2xl bg-warning/10 border border-warning/30 p-5">
        <h2 className="text-lg font-semibold text-warning">⚠️ Not Medical Advice</h2>
        <p className="text-sm text-muted-foreground">
          Protocol is an <strong>educational tool</strong> for personal experimentation and data organization.
          Protocols generated by AI are <strong>not medical advice</strong>, diagnosis, or treatment.
          Always consult a licensed physician before making changes to your diet, exercise, supplements, or medications.
          Never ignore professional medical advice or delay seeking it because of something you read here.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-accent">Age Requirement</h2>
        <p className="text-sm text-muted-foreground">You must be 18 or older to use Protocol. Users under 18 may use the app only with parental supervision and should consult a pediatrician.</p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-accent">Your Responsibilities</h2>
        <ul className="text-sm text-muted-foreground list-disc pl-6 space-y-1">
          <li>Enter accurate biomarker values and health data</li>
          <li>Consult your doctor before acting on any recommendations</li>
          <li>Report adverse reactions to supplements to your doctor immediately</li>
          <li>Do not share your account with others</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-accent">Liability</h2>
        <p className="text-sm text-muted-foreground">Protocol is provided &quot;as is&quot; without warranty. We are not liable for any health outcomes, direct or indirect, resulting from use of this tool. You use Protocol at your own risk.</p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-accent">AI-Generated Content</h2>
        <p className="text-sm text-muted-foreground">Protocols are generated by large language models (Groq Llama, Anthropic Claude). AI can produce errors or hallucinations. Always verify recommendations with medical professionals before acting.</p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-accent">Changes</h2>
        <p className="text-sm text-muted-foreground">We may update these terms. Continued use after updates constitutes acceptance.</p>
      </section>

      <div className="pt-6 border-t border-card-border">
        <Link href="/" className="text-sm text-accent hover:underline">← Back to home</Link>
      </div>
    </div>
  );
}
