import { Metadata } from 'next';
import Link from 'next/link';
import { SITE_URL } from '@/lib/config';

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  // Title carries the score so Twitter shows "Longevity score 84/100" in unfurls
  // even before the OG image renders. Fallback if the share is missing.
  try {
    const res = await fetch(`${SITE_URL}/api/share?slug=${slug}`, { cache: 'no-store' });
    if (!res.ok) throw new Error('not found');
    const data = await res.json();
    const score = data?.longevity_score ?? null;
    const bioAge = data?.protocol_json?.diagnostic?.biologicalAge ?? data?.biological_age ?? null;
    const chronoAge = data?.protocol_json?.diagnostic?.chronologicalAge ?? null;
    const titleParts = [
      score ? `Longevity score ${score}/100` : null,
      bioAge && chronoAge ? `bio ${typeof bioAge === 'number' ? bioAge.toFixed(1) : bioAge}y vs ${chronoAge} chrono` : null,
    ].filter(Boolean).join(' · ');
    const title = titleParts ? `${titleParts} — Protocol` : 'Shared Protocol';
    const description = 'AI-generated longevity protocol — biomarkers, supplements, exercise, sleep, nutrition. Built from real blood work.';
    return {
      title,
      description,
      openGraph: { title, description, type: 'article' },
      twitter: { card: 'summary_large_image', title, description },
    };
  } catch {
    return {
      title: 'Shared Protocol — Protocol AI Engine',
      description: 'A personalized longevity protocol generated by Protocol AI.',
    };
  }
}

async function getSharedProtocol(slug: string) {
  try {
    const res = await fetch(`${SITE_URL}/api/share?slug=${slug}`, { cache: 'no-store' });
    if (!res.ok) return null;
    return res.json();
  } catch {
    return null;
  }
}

export default async function SharePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const data = await getSharedProtocol(slug);

  if (!data || !data.protocol_json) {
    return (
      <div className="min-h-dvh flex items-center justify-center px-6">
        <div className="text-center space-y-4">
          <p className="text-4xl">🔗</p>
          <p className="text-xl font-bold">Protocol not found</p>
          <p className="text-sm text-muted-foreground">This link may have expired or been removed.</p>
          <Link href="/" className="inline-block px-6 py-3 bg-accent text-black rounded-xl font-semibold text-sm">Get Your Own Protocol</Link>
        </div>
      </div>
    );
  }

  const p = data.protocol_json;
  const diag = p.diagnostic;
  const score = data.longevity_score;
  const bioAge = data.biological_age;

  return (
    <div className="max-w-3xl mx-auto px-4 py-8 space-y-6">
      {/* Header */}
      <div className="text-center space-y-2">
        <Link href="/" className="text-accent font-bold text-lg">Protocol</Link>
        <h1 className="text-2xl font-bold">Shared Longevity Protocol</h1>
      </div>

      {/* Diagnostic hero */}
      <div className="rounded-2xl bg-card border border-card-border p-6">
        <div className="grid grid-cols-3 gap-3 text-center">
          <div className="p-4 rounded-xl bg-background border border-card-border">
            <p className="text-3xl font-bold font-mono text-accent">{score}</p>
            <p className="text-[10px] text-muted mt-1">LONGEVITY SCORE</p>
          </div>
          <div className="p-4 rounded-xl bg-background border border-card-border">
            <p className="text-3xl font-bold font-mono">{bioAge}</p>
            <p className="text-[10px] text-muted mt-1">BIO AGE</p>
          </div>
          <div className="p-4 rounded-xl bg-background border border-card-border">
            <p className="text-3xl font-bold font-mono">{diag?.chronologicalAge}</p>
            <p className="text-[10px] text-muted mt-1">CHRONO AGE</p>
          </div>
        </div>
        {diag?.summary && <p className="text-sm text-muted-foreground mt-4 text-center">{diag.summary}</p>}
      </div>

      {/* Biomarkers */}
      {p.biomarkerReadout?.length > 0 && (
        <div className="rounded-2xl bg-card border border-card-border p-5">
          <h2 className="text-lg font-semibold mb-4">🔬 Biomarkers</h2>
          <div className="space-y-2">
            {p.biomarkerReadout.map((b: Record<string, unknown>, i: number) => (
              <div key={i} className="flex items-center justify-between p-3 rounded-xl bg-background border border-card-border">
                <span className="text-sm font-medium">{b.shortName as string || b.name as string}</span>
                <div className="flex items-center gap-2">
                  <span className="text-base font-bold font-mono">{b.value as number}</span>
                  <span className="text-[10px] text-muted">{b.unit as string}</span>
                  <span className="text-[9px] font-mono px-2 py-0.5 rounded-full bg-accent/10 text-accent">{b.classification as string}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Supplements */}
      {p.supplements?.length > 0 && (
        <div className="rounded-2xl bg-card border border-card-border p-5">
          <h2 className="text-lg font-semibold mb-4">💊 Supplement Stack</h2>
          <div className="space-y-2">
            {p.supplements.map((s: Record<string, unknown>, i: number) => (
              <div key={i} className="p-3 rounded-xl bg-background border border-card-border">
                <div className="flex items-center justify-between">
                  <span className="text-sm font-semibold">{s.name as string}</span>
                  <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-accent/10 text-accent">{s.priority as string}</span>
                </div>
                <p className="text-[10px] text-muted-foreground mt-1">{s.dose as string} • {s.timing as string}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Roadmap */}
      {p.roadmap?.length > 0 && (
        <div className="rounded-2xl bg-card border border-card-border p-5">
          <h2 className="text-lg font-semibold mb-4">🗺️ 12-Week Roadmap</h2>
          {p.roadmap.map((r: Record<string, unknown>, i: number) => (
            <div key={i} className="flex gap-3 mb-3">
              <div className="w-2 h-2 rounded-full bg-accent mt-1.5 shrink-0" />
              <div>
                <p className="text-sm font-medium text-accent">{r.week as string}</p>
                {(r.actions as string[])?.map((a: string, j: number) => <p key={j} className="text-xs text-muted-foreground">• {a}</p>)}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* CTA */}
      <div className="text-center py-8 space-y-4">
        <p className="text-lg font-bold">Want your own personalized protocol?</p>
        <Link href="/" className="inline-block px-8 py-3 bg-accent text-black rounded-xl font-semibold text-sm">Get Your Protocol — Free</Link>
        <p className="text-[10px] text-muted">Disclaimer: This is not medical advice. Consult your doctor before making changes.</p>
      </div>
    </div>
  );
}
