import { BiomarkerReference } from '../types';

export const BIOMARKER_DB: BiomarkerReference[] = [
  {
    code: 'HSCRP', name: 'High-Sensitivity C-Reactive Protein', shortName: 'hsCRP',
    category: 'INFLAMMATION', unit: 'mg/L',
    longevityOptimalLow: 0, longevityOptimalHigh: 0.5,
    populationAvgLow: 1.0, populationAvgHigh: 3.0,
    bryanJohnsonValue: 0.1,
    description: 'Cel mai important marker de inflamație sistemică. Inflamația cronică accelerează toate bolile legate de vârstă.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: [] },
    interventionsIfHigh: {
      lifestyle: ['Reduce grăsimea viscerală', 'Crește omega-3', 'Exerciții regulate', 'Gestionează stresul'],
      supplements: [
        { name: 'Omega-3 EPA/DHA', dose: '2-3g zilnic', priority: 'MUST' },
        { name: 'Curcumină', dose: '500-1000mg cu piperină', priority: 'STRONG' },
      ],
      foods_add: ['Pește gras 3x/săpt', 'Fructe de pădure zilnic', 'Ulei de măsline'],
      foods_avoid: ['Uleiuri de semințe', 'Carne procesată', 'Zahăr rafinat'],
      medical: ['Verifică infecții ascunse', 'Control dentar dacă >2.0'],
    },
    retestIntervalWeeks: 4,
  },
  {
    code: 'GLUC', name: 'Fasting Glucose', shortName: 'Glucoză',
    category: 'GLUCOSE_INSULIN', unit: 'mg/dL',
    longevityOptimalLow: 72, longevityOptimalHigh: 85,
    populationAvgLow: 70, populationAvgHigh: 100,
    bryanJohnsonValue: 74,
    description: 'Glicemia à jeun reflectă metabolismul glucozei. Niveluri crescute cronic accelerează glicarea și îmbătrânirea.',
    interventionsIfLow: { lifestyle: ['Mese regulate', 'Carbohidrați complecși'], supplements: [], foods_add: ['Fructe', 'Cereale integrale'], foods_avoid: [], medical: ['Verifică funcția hepatică'] },
    interventionsIfHigh: {
      lifestyle: ['Restricție calorică moderată', 'Exerciții post-prandiale', 'Time-restricted eating'],
      supplements: [
        { name: 'Berberină', dose: '500mg x2/zi', priority: 'STRONG' },
        { name: 'Crom picolinat', dose: '200mcg/zi', priority: 'OPTIONAL' },
      ],
      foods_add: ['Leguminoase', 'Vegetale cu frunze', 'Scorțișoară'],
      foods_avoid: ['Pâine albă', 'Sucuri', 'Dulciuri'],
      medical: ['Discută metformină cu medicul dacă >100', 'Test OGTT dacă >95'],
    },
    retestIntervalWeeks: 12,
  },
  {
    code: 'HBA1C', name: 'Hemoglobina Glicată', shortName: 'HbA1c',
    category: 'GLUCOSE_INSULIN', unit: '%',
    longevityOptimalLow: 4.5, longevityOptimalHigh: 5.2,
    populationAvgLow: 4.8, populationAvgHigh: 5.6,
    bryanJohnsonValue: 4.8,
    description: 'Media glicemiei din ultimele 3 luni. Gold standard pentru evaluarea metabolismului glucozei pe termen lung.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: ['Investigare anemie'] },
    interventionsIfHigh: {
      lifestyle: ['Exerciții aerobice zilnice', 'Reducerea carbohidraților rafinați', 'Somn 7-9 ore'],
      supplements: [
        { name: 'Berberină', dose: '1000-1500mg/zi', priority: 'MUST' },
        { name: 'Magneziu glicinат', dose: '400mg seara', priority: 'STRONG' },
      ],
      foods_add: ['Fibre solubile', 'Oțet de mere înainte de mese'],
      foods_avoid: ['Cereale rafinate', 'Băuturi dulci'],
      medical: ['Consultație endocrinolog dacă >5.7', 'URGENT: medic dacă >6.5 (diabet)'],
    },
    retestIntervalWeeks: 16,
  },
  {
    code: 'LDL', name: 'LDL Cholesterol', shortName: 'LDL-C',
    category: 'LIPIDS', unit: 'mg/dL',
    longevityOptimalLow: 50, longevityOptimalHigh: 100,
    populationAvgLow: 100, populationAvgHigh: 160,
    bryanJohnsonValue: 53,
    description: 'Colesterolul LDL oxidat pătrunde în peretele arterial. ApoB este mai precis, dar LDL rămâne esențial.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: ['Ouă', 'Avocado'], foods_avoid: [], medical: ['Verifică funcția hepatică'] },
    interventionsIfHigh: {
      lifestyle: ['Dietă plant-heavy', 'Exerciții aerobice 150min/săpt', 'Reduce grăsimi saturate'],
      supplements: [
        { name: 'Citrus bergamot', dose: '500mg x2/zi', priority: 'STRONG' },
        { name: 'Fibre psyllium', dose: '5-10g/zi', priority: 'MUST' },
      ],
      foods_add: ['Ovăz', 'Nuci', 'Leguminoase', 'Ulei de măsline'],
      foods_avoid: ['Unt în exces', 'Carne roșie frecventă', 'Brânzeturi grase'],
      medical: ['Discută statin dacă >160 sau risc CV crescut', 'Test ApoB pentru precizie'],
    },
    retestIntervalWeeks: 12,
  },
  {
    code: 'HDL', name: 'HDL Cholesterol', shortName: 'HDL-C',
    category: 'LIPIDS', unit: 'mg/dL',
    longevityOptimalLow: 55, longevityOptimalHigh: 90,
    populationAvgLow: 40, populationAvgHigh: 60,
    bryanJohnsonValue: 67,
    description: 'Colesterolul „bun" — transportă colesterolul înapoi la ficat. Nivel optim protejează cardiovascular.',
    interventionsIfLow: {
      lifestyle: ['Exerciții regulate (cresc HDL 5-10%)', 'Reduce carbohidrații rafinați'],
      supplements: [{ name: 'Niacină (B3)', dose: '500mg/zi', priority: 'OPTIONAL' }],
      foods_add: ['Pește gras', 'Ulei de măsline', 'Avocado', 'Nuci'],
      foods_avoid: ['Trans fats', 'Zahăr rafinat'],
      medical: ['Verifică risc metabolic'],
    },
    interventionsIfHigh: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: ['HDL foarte mare (>100) poate fi disfuncțional'] },
    retestIntervalWeeks: 12,
  },
  {
    code: 'TRIG', name: 'Trigliceride', shortName: 'TG',
    category: 'LIPIDS', unit: 'mg/dL',
    longevityOptimalLow: 30, longevityOptimalHigh: 80,
    populationAvgLow: 80, populationAvgHigh: 150,
    bryanJohnsonValue: 44,
    description: 'Trigliceridele reflectă metabolismul carbohidraților și rezistența la insulină. TG/HDL ratio < 1.5 = ideal.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: [] },
    interventionsIfHigh: {
      lifestyle: ['Reduce carbohidrați rafinați dramatic', 'Elimină alcoolul', 'Exerciții zilnice'],
      supplements: [
        { name: 'Omega-3 EPA/DHA', dose: '2-4g/zi', priority: 'MUST' },
        { name: 'Berberină', dose: '500mg x2/zi', priority: 'STRONG' },
      ],
      foods_add: ['Pește gras', 'Nuci', 'Semințe de in'],
      foods_avoid: ['Alcool', 'Sucuri de fructe', 'Pâine albă', 'Orez alb'],
      medical: ['Verifică rezistență la insulină', 'Panel lipidic extins'],
    },
    retestIntervalWeeks: 8,
  },
  {
    code: 'VITD', name: '25-Hydroxyvitamin D', shortName: 'Vitamina D',
    category: 'VITAMINS', unit: 'ng/mL',
    longevityOptimalLow: 50, longevityOptimalHigh: 80,
    populationAvgLow: 20, populationAvgHigh: 40,
    bryanJohnsonValue: 72,
    description: 'Hormoni steroizi esențiali. 70% din europeni sunt deficienți. Impact: imunitate, oase, dispoziție, cancer, longevitate.',
    interventionsIfLow: {
      lifestyle: ['Expunere solară 15-30 min/zi', 'Mese cu grăsimi (absorție)'],
      supplements: [
        { name: 'Vitamina D3', dose: '4000-5000 IU/zi', priority: 'MUST' },
        { name: 'Vitamina K2 MK-7', dose: '100-200mcg/zi', priority: 'MUST' },
      ],
      foods_add: ['Pește gras', 'Ciuperci expuse la UV', 'Ouă'],
      foods_avoid: [],
      medical: ['Retestare la 12 săptămâni', 'Verifică calciu și PTH'],
    },
    interventionsIfHigh: { lifestyle: ['Reduce suplimentarea'], supplements: [], foods_add: [], foods_avoid: [], medical: ['Verifică calciu seric dacă >100'] },
    retestIntervalWeeks: 12,
  },
  {
    code: 'TSH', name: 'Thyroid Stimulating Hormone', shortName: 'TSH',
    category: 'THYROID', unit: 'mIU/L',
    longevityOptimalLow: 0.5, longevityOptimalHigh: 2.0,
    populationAvgLow: 0.4, populationAvgHigh: 4.0,
    bryanJohnsonValue: 1.4,
    description: 'TSH reflectă funcția tiroidiană. Chiar și în „interval normal", TSH >2.5 poate indica hipotiroidism subclinic.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: ['URGENT: Verifică hipertiroidism', 'Test FT3, FT4, anticorpi'] },
    interventionsIfHigh: {
      lifestyle: ['Gestionează stresul', 'Somn adecvat', 'Exerciții moderate'],
      supplements: [
        { name: 'Seleniu', dose: '200mcg/zi', priority: 'STRONG' },
        { name: 'Zinc', dose: '25mg/zi', priority: 'STRONG' },
      ],
      foods_add: ['Nuci de Brazilia (seleniu)', 'Pește (iod)'],
      foods_avoid: ['Soia în exces', 'Crucifere crude în exces dacă hipotiroid'],
      medical: ['Endocrinolog dacă >4.0', 'Test anti-TPO, FT4'],
    },
    retestIntervalWeeks: 8,
  },
  {
    code: 'FERRITIN', name: 'Feritina', shortName: 'Feritină',
    category: 'MINERALS', unit: 'ng/mL',
    longevityOptimalLow: 40, longevityOptimalHigh: 100,
    populationAvgLow: 30, populationAvgHigh: 300,
    bryanJohnsonValue: 54,
    description: 'Depozit de fier. Prea puțin = anemie. Prea mult = stres oxidativ și accelerarea îmbătrânirii. Bryan donează sânge regulat.',
    interventionsIfLow: {
      lifestyle: ['Combină fierul cu vitamina C'],
      supplements: [{ name: 'Fier bisglicinат', dose: '25-50mg/zi', priority: 'MUST' }],
      foods_add: ['Carne roșie', 'Spanac', 'Linte'],
      foods_avoid: ['Ceai/cafea la mese (inhibă absorția)'],
      medical: ['Investigare cauza: pierderi, malabsorbție'],
    },
    interventionsIfHigh: {
      lifestyle: ['Donare sânge la 3 luni', 'Reduce carnea roșie'],
      supplements: [],
      foods_add: ['Ceai verde (chelator ușor)'],
      foods_avoid: ['Suplimente cu fier', 'Carne roșie frecventă'],
      medical: ['Verifică hemochromatoză dacă >300', 'Test genetic HFE'],
    },
    retestIntervalWeeks: 12,
  },
  {
    code: 'B12', name: 'Vitamina B12', shortName: 'B12',
    category: 'VITAMINS', unit: 'pg/mL',
    longevityOptimalLow: 500, longevityOptimalHigh: 1000,
    populationAvgLow: 200, populationAvgHigh: 900,
    bryanJohnsonValue: 680,
    description: 'Esențial pentru funcția nervoasă, formarea ADN, și energie. Deficiența e frecventă la vegetarieni și vârstnici.',
    interventionsIfLow: {
      lifestyle: [],
      supplements: [{ name: 'Metilcobalamină B12', dose: '1000mcg/zi', priority: 'MUST' }],
      foods_add: ['Ficat', 'Sardine', 'Ouă'],
      foods_avoid: [],
      medical: ['Verifică acid folic și homocisteină', 'Test anticorpi factor intrinsec'],
    },
    interventionsIfHigh: { lifestyle: ['Reduce suplimentarea B12'], supplements: [], foods_add: [], foods_avoid: [], medical: ['B12 foarte mare poate indica probleme hepatice'] },
    retestIntervalWeeks: 12,
  },
  {
    code: 'TESTO', name: 'Testosteron Total', shortName: 'Testosteron',
    category: 'HORMONES', unit: 'ng/dL',
    longevityOptimalLow: 500, longevityOptimalHigh: 900,
    populationAvgLow: 300, populationAvgHigh: 1000,
    bryanJohnsonValue: 750,
    description: 'Hormon anabolic cheie. Scade 1-2%/an după 30 ani. Impact: masă musculară, oase, energie, cogniție, dispoziție.',
    interventionsIfLow: {
      lifestyle: ['Somn 7-9 ore', 'Antrenament de forță', 'Reduce grăsimea corporală', 'Gestionează stresul'],
      supplements: [
        { name: 'Zinc', dose: '30mg/zi', priority: 'MUST' },
        { name: 'Vitamina D3', dose: '4000 IU/zi', priority: 'STRONG' },
        { name: 'Ashwagandha KSM-66', dose: '600mg/zi', priority: 'STRONG' },
      ],
      foods_add: ['Ouă', 'Stridii', 'Nuci de Brazilia'],
      foods_avoid: ['Alcool', 'Soia procesată', 'Plastificianți (BPA)'],
      medical: ['Endocrinolog dacă <300', 'Verifică SHBG, LH, FSH, prolactină'],
    },
    interventionsIfHigh: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: ['Verifică sursa dacă >1100 fără TRT'] },
    retestIntervalWeeks: 12,
  },
  {
    code: 'ALT', name: 'Alanin Aminotransferaza', shortName: 'ALT (TGP)',
    category: 'LIVER', unit: 'U/L',
    longevityOptimalLow: 10, longevityOptimalHigh: 25,
    populationAvgLow: 10, populationAvgHigh: 40,
    bryanJohnsonValue: 16,
    description: 'Marker de sănătate hepatică. ALT crescut indică inflamație hepatică — frecvent din grăsime hepatică non-alcoolică.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: [] },
    interventionsIfHigh: {
      lifestyle: ['Reduce alcoolul', 'Slăbire dacă supraponderal', 'Exerciții regulate'],
      supplements: [
        { name: 'NAC (N-Acetilcisteină)', dose: '600mg x2/zi', priority: 'STRONG' },
        { name: 'Cardo de lapte (Silimarina)', dose: '300mg/zi', priority: 'OPTIONAL' },
      ],
      foods_add: ['Broccoli', 'Varză', 'Ceai verde'],
      foods_avoid: ['Alcool', 'Fructoză în exces', 'Alimente prăjite'],
      medical: ['Ecografie hepatică dacă >40', 'Verifică hepatita B/C'],
    },
    retestIntervalWeeks: 8,
  },
  {
    code: 'CREAT', name: 'Creatinina', shortName: 'Creatinină',
    category: 'KIDNEY', unit: 'mg/dL',
    longevityOptimalLow: 0.7, longevityOptimalHigh: 1.1,
    populationAvgLow: 0.6, populationAvgHigh: 1.2,
    bryanJohnsonValue: 0.93,
    description: 'Marker al funcției renale. eGFR calculat din creatinină estimează rata de filtrare glomerulară.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: ['Poate indica masă musculară scăzută'] },
    interventionsIfHigh: {
      lifestyle: ['Hidratare adecvată (2-3L/zi)', 'Reduce proteinele dacă foarte crescut'],
      supplements: [],
      foods_add: ['Apă', 'Fructe cu apă (pepene)'],
      foods_avoid: ['Suplimente creatină dacă eGFR scăzut'],
      medical: ['URGENT: Nefrolog dacă >1.5', 'Calcul eGFR', 'Verifică cistatina C'],
    },
    retestIntervalWeeks: 12,
  },
  {
    code: 'HOMOCYS', name: 'Homocisteina', shortName: 'Homocisteină',
    category: 'INFLAMMATION', unit: 'µmol/L',
    longevityOptimalLow: 5, longevityOptimalHigh: 8,
    populationAvgLow: 5, populationAvgHigh: 15,
    bryanJohnsonValue: 6.2,
    description: 'Aminoacid toxic la niveluri ridicate. Marker independent de risc cardiovascular. Legat de folat, B12, B6.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: [] },
    interventionsIfHigh: {
      lifestyle: ['Reduce cafeaua', 'Nu fuma'],
      supplements: [
        { name: 'Metilfolat (5-MTHF)', dose: '400-800mcg/zi', priority: 'MUST' },
        { name: 'Metilcobalamină B12', dose: '1000mcg/zi', priority: 'MUST' },
        { name: 'P5P (B6 activat)', dose: '50mg/zi', priority: 'STRONG' },
      ],
      foods_add: ['Legume cu frunze verzi', 'Leguminoase', 'Avocado'],
      foods_avoid: ['Cafea excesivă', 'Alcool'],
      medical: ['Test MTHFR dacă >12', 'Verifică B12 și folat seric'],
    },
    retestIntervalWeeks: 8,
  },
  {
    code: 'WBC', name: 'White Blood Cells', shortName: 'Leucocite',
    category: 'BLOOD_COUNT', unit: '×10³/µL',
    longevityOptimalLow: 4.0, longevityOptimalHigh: 6.0,
    populationAvgLow: 4.5, populationAvgHigh: 11.0,
    bryanJohnsonValue: 4.7,
    description: 'Leucocitele ridicate (chiar în „normal") indică inflamație cronică. WBC <6 asociat cu longevitate crescută.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: ['Investigare dacă <3.5'] },
    interventionsIfHigh: {
      lifestyle: ['Exerciții anti-inflamatorii', 'Somn adecvat', 'Reduce stresul'],
      supplements: [{ name: 'Omega-3', dose: '2g/zi', priority: 'STRONG' }],
      foods_add: ['Curcuma', 'Ghimbir', 'Ceai verde'],
      foods_avoid: ['Alimente procesate', 'Zahăr'],
      medical: ['Excludere infecție dacă >11', 'Verifică formula leucocitară'],
    },
    retestIntervalWeeks: 8,
  },
  {
    code: 'HGB', name: 'Hemoglobina', shortName: 'Hemoglobină',
    category: 'BLOOD_COUNT', unit: 'g/dL',
    longevityOptimalLow: 13.5, longevityOptimalHigh: 15.5,
    populationAvgLow: 12.0, populationAvgHigh: 17.0,
    bryanJohnsonValue: 14.8,
    description: 'Capacitatea de transport a oxigenului. Scăzut = anemie, oboseală. Crescut = deshidratare sau policitemie.',
    interventionsIfLow: {
      lifestyle: ['Mese bogate în fier cu vitamina C'],
      supplements: [{ name: 'Fier bisglicinат', dose: '25mg/zi', priority: 'MUST' }],
      foods_add: ['Carne roșie', 'Spanac', 'Linte', 'Sfeclă'],
      foods_avoid: ['Cafea/ceai la mese'],
      medical: ['Investigare cauza anemiei: fier, B12, folat, sângerare'],
    },
    interventionsIfHigh: { lifestyle: ['Hidratare', 'Donare sânge'], supplements: [], foods_add: [], foods_avoid: [], medical: ['Verifică policitemie dacă >17'] },
    retestIntervalWeeks: 12,
  },
  {
    code: 'INSULIN', name: 'Insulina à jeun', shortName: 'Insulină',
    category: 'GLUCOSE_INSULIN', unit: 'µIU/mL',
    longevityOptimalLow: 2, longevityOptimalHigh: 5,
    populationAvgLow: 2, populationAvgHigh: 25,
    bryanJohnsonValue: 3.2,
    description: 'Insulina à jeun e cel mai precoce marker de rezistență la insulină — apare ÎNAINTE ca glicemia să crească.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: [] },
    interventionsIfHigh: {
      lifestyle: ['Time-restricted eating (16:8)', 'Exerciții HIIT + forță', 'Mers 30 min după mese'],
      supplements: [
        { name: 'Berberină', dose: '500mg x2/zi cu mesele', priority: 'MUST' },
        { name: 'Magneziu', dose: '400mg seara', priority: 'STRONG' },
        { name: 'Crom picolinat', dose: '200mcg/zi', priority: 'OPTIONAL' },
      ],
      foods_add: ['Oțet de mere', 'Scorțișoară', 'Fibre', 'Proteine la fiecare masă'],
      foods_avoid: ['Carbohidrați simpli', 'Sucuri', 'Cereale procesate'],
      medical: ['Test HOMA-IR', 'Discută metformină dacă >10'],
    },
    retestIntervalWeeks: 12,
  },
  {
    code: 'MAGNE', name: 'Magneziu seric', shortName: 'Magneziu',
    category: 'MINERALS', unit: 'mg/dL',
    longevityOptimalLow: 2.0, longevityOptimalHigh: 2.4,
    populationAvgLow: 1.7, populationAvgHigh: 2.2,
    bryanJohnsonValue: 2.2,
    description: 'Cofactor în 300+ reacții enzimatice. 50% din populație e deficientă. Serul reflectă doar 1% din totalul din corp.',
    interventionsIfLow: {
      lifestyle: ['Băi cu sare Epsom', 'Reduce stresul'],
      supplements: [{ name: 'Magneziu glicinат', dose: '400mg seara', priority: 'MUST' }],
      foods_add: ['Ciocolată neagră >85%', 'Semințe de dovleac', 'Avocado', 'Spanac'],
      foods_avoid: ['Alcool', 'Cafea excesivă'],
      medical: ['Test magneziu eritrocitar (mai precis)'],
    },
    interventionsIfHigh: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: ['Verifică funcția renală'] },
    retestIntervalWeeks: 12,
  },
  {
    code: 'FOLAT', name: 'Acid Folic (Folat seric)', shortName: 'Folat',
    category: 'VITAMINS', unit: 'ng/mL',
    longevityOptimalLow: 15, longevityOptimalHigh: 40,
    populationAvgLow: 3, populationAvgHigh: 20,
    bryanJohnsonValue: 28,
    description: 'Esențial pentru metilare, sinteza ADN, și conversia homocisteinei. Deficiența crește riscul cardiovascular și cognitiv.',
    interventionsIfLow: {
      lifestyle: [],
      supplements: [{ name: 'Metilfolat (5-MTHF)', dose: '400-800mcg/zi', priority: 'MUST' }],
      foods_add: ['Spanac', 'Linte', 'Sparanghel', 'Broccoli'],
      foods_avoid: [],
      medical: ['Test MTHFR C677T', 'Verifică homocisteină și B12'],
    },
    interventionsIfHigh: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: [] },
    retestIntervalWeeks: 12,
  },
  {
    code: 'OMEGA3', name: 'Omega-3 Index', shortName: 'Omega-3 Index',
    category: 'INFLAMMATION', unit: '%',
    longevityOptimalLow: 8, longevityOptimalHigh: 12,
    populationAvgLow: 4, populationAvgHigh: 6,
    bryanJohnsonValue: 10.5,
    description: 'Procentul EPA+DHA din membrana eritrocitară. <8% = risc cardiovascular crescut. Bryan ia 2g EPA/zi.',
    interventionsIfLow: {
      lifestyle: ['Pește gras 3-4x/săpt'],
      supplements: [{ name: 'Omega-3 EPA/DHA', dose: '2-3g/zi', priority: 'MUST' }],
      foods_add: ['Somon', 'Sardine', 'Macrou', 'Semințe de chia'],
      foods_avoid: ['Uleiuri omega-6 (floarea soarelui, porumb)'],
      medical: ['Retestare la 3 luni'],
    },
    interventionsIfHigh: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: [] },
    retestIntervalWeeks: 12,
  },
];

export function getBiomarkerRef(code: string): BiomarkerReference | undefined {
  return BIOMARKER_DB.find((b) => b.code === code);
}

export const BIOMARKER_CATEGORIES = [...new Set(BIOMARKER_DB.map((b) => b.category))];
