import { BiomarkerReference } from '../types';

// ═══════════════════════════════════════════════════════════════
// BIOMARKER REFERENCE DATABASE v2 — 38 markers
// Sources: Bryan Johnson Blueprint, Peter Attia, Rhonda Patrick,
// longevity literature, clinical guidelines with longevity-optimal
// ranges (tighter than standard lab ranges)
// ═══════════════════════════════════════════════════════════════

export const BIOMARKER_DB: BiomarkerReference[] = [
  // ══════ INFLAMMATION ══════
  {
    code: 'HSCRP', name: 'High-Sensitivity C-Reactive Protein', shortName: 'hsCRP',
    category: 'INFLAMMATION', unit: 'mg/L',
    longevityOptimalLow: 0, longevityOptimalHigh: 0.5,
    populationAvgLow: 1.0, populationAvgHigh: 3.0,
    bryanJohnsonValue: 0.1,
    description: 'The single most important inflammation marker. Bryan Johnson calls it his #1 priority. Chronic low-grade inflammation drives ALL major age-related diseases: heart disease, cancer, neurodegeneration, diabetes.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: [] },
    interventionsIfHigh: {
      lifestyle: ['Reduce visceral fat (waist circumference)', 'Exercise 150+ min/week', 'Sleep 7-9 hours', 'Stress management daily'],
      supplements: [
        { name: 'Omega-3 EPA/DHA', dose: '2-3g daily', priority: 'MUST' },
        { name: 'Curcumin with piperine', dose: '1000mg daily', priority: 'STRONG' },
        { name: 'NAC', dose: '1200mg daily', priority: 'STRONG' },
      ],
      foods_add: ['Fatty fish 3x/week', 'Berries daily', 'Extra virgin olive oil 2-3 tbsp', 'Turmeric', 'Green tea'],
      foods_avoid: ['Seed oils', 'Processed meat', 'Refined sugar', 'Ultra-processed food', 'Alcohol'],
      medical: ['Check for hidden infections if >2.0', 'Dental workup', 'Check gut health if >3.0'],
    },
    retestIntervalWeeks: 4,
  },
  {
    code: 'HOMOCYS', name: 'Homocysteine', shortName: 'Homocysteine',
    category: 'INFLAMMATION', unit: 'µmol/L',
    longevityOptimalLow: 5, longevityOptimalHigh: 8,
    populationAvgLow: 5, populationAvgHigh: 15,
    bryanJohnsonValue: 6.2,
    description: 'Toxic amino acid at high levels. Independent cardiovascular risk factor. Directly linked to folate, B12, and B6 status. Also affects brain health and dementia risk.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: [] },
    interventionsIfHigh: {
      lifestyle: ['Reduce coffee', 'Stop smoking', 'Exercise regularly'],
      supplements: [
        { name: 'Methylfolate (5-MTHF)', dose: '800mcg daily', priority: 'MUST' },
        { name: 'Methylcobalamin B12', dose: '1000mcg daily', priority: 'MUST' },
        { name: 'P5P (active B6)', dose: '50mg daily', priority: 'STRONG' },
      ],
      foods_add: ['Dark leafy greens', 'Legumes', 'Avocado', 'Eggs'],
      foods_avoid: ['Excessive coffee', 'Alcohol'],
      medical: ['MTHFR genetic test if >12', 'Check B12 and folate levels'],
    },
    retestIntervalWeeks: 8,
  },
  {
    code: 'OMEGA3', name: 'Omega-3 Index', shortName: 'Omega-3 Index',
    category: 'INFLAMMATION', unit: '%',
    longevityOptimalLow: 8, longevityOptimalHigh: 12,
    populationAvgLow: 4, populationAvgHigh: 6,
    bryanJohnsonValue: 10.5,
    description: 'Percentage of EPA+DHA in red blood cell membranes. Below 8% = elevated cardiovascular risk. One of the strongest modifiable longevity markers. Most people are severely deficient.',
    interventionsIfLow: {
      lifestyle: ['Eat fatty fish 3-4x/week (salmon, sardines, mackerel)'],
      supplements: [{ name: 'Omega-3 EPA/DHA', dose: '2-3g daily', priority: 'MUST' }],
      foods_add: ['Wild salmon', 'Sardines', 'Mackerel', 'Chia seeds', 'Walnuts'],
      foods_avoid: ['Omega-6 oils (sunflower, corn, soybean)', 'Fried food'],
      medical: ['Retest in 12 weeks'],
    },
    interventionsIfHigh: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: [] },
    retestIntervalWeeks: 12,
  },

  // ══════ GLUCOSE & INSULIN ══════
  {
    code: 'GLUC', name: 'Fasting Glucose', shortName: 'Glucose',
    category: 'GLUCOSE_INSULIN', unit: 'mg/dL',
    longevityOptimalLow: 72, longevityOptimalHigh: 85,
    populationAvgLow: 70, populationAvgHigh: 100,
    bryanJohnsonValue: 74,
    description: 'Fasting blood glucose reflects glucose metabolism. Chronically elevated levels accelerate glycation and aging. Even "normal" levels above 90 increase long-term risk.',
    interventionsIfLow: { lifestyle: ['Regular meals', 'Complex carbs'], supplements: [], foods_add: ['Fruit', 'Whole grains'], foods_avoid: [], medical: ['Check liver function if <65'] },
    interventionsIfHigh: {
      lifestyle: ['Time-restricted eating (16:8)', 'Walk 30 min after every meal', 'Reduce refined carbs', 'Strength training 3x/week'],
      supplements: [
        { name: 'Berberine', dose: '500mg 2x/day with meals', priority: 'STRONG' },
        { name: 'Chromium picolinate', dose: '200mcg daily', priority: 'OPTIONAL' },
        { name: 'Magnesium glycinate', dose: '400mg evening', priority: 'STRONG' },
      ],
      foods_add: ['Legumes', 'Leafy greens', 'Cinnamon', 'Apple cider vinegar before meals'],
      foods_avoid: ['White bread', 'Juice', 'Sweets', 'White rice'],
      medical: ['Discuss metformin if >100', 'OGTT if >95', 'URGENT: if >126 = diabetes'],
    },
    retestIntervalWeeks: 12,
  },
  {
    code: 'HBA1C', name: 'Glycated Hemoglobin', shortName: 'HbA1c',
    category: 'GLUCOSE_INSULIN', unit: '%',
    longevityOptimalLow: 4.5, longevityOptimalHigh: 5.2,
    populationAvgLow: 4.8, populationAvgHigh: 5.6,
    bryanJohnsonValue: 4.8,
    description: 'Average blood sugar over 3 months. The gold standard for long-term glucose metabolism. Bryan targets <5.0. Every 0.1% reduction matters.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: ['Investigate if <4.0 — possible anemia'] },
    interventionsIfHigh: {
      lifestyle: ['Daily aerobic exercise', 'Reduce refined carbs aggressively', 'Sleep 7-9 hours', 'Time-restricted eating'],
      supplements: [
        { name: 'Berberine', dose: '1000-1500mg/day split doses', priority: 'MUST' },
        { name: 'Magnesium glycinate', dose: '400mg evening', priority: 'STRONG' },
        { name: 'Chromium', dose: '200mcg daily', priority: 'OPTIONAL' },
      ],
      foods_add: ['Soluble fiber (oats, psyllium)', 'Apple cider vinegar', 'Cinnamon'],
      foods_avoid: ['Refined grains', 'Sugary drinks', 'Fruit juice'],
      medical: ['Endocrinologist if >5.7 (prediabetic)', 'URGENT: if >6.5 (diabetes)'],
    },
    retestIntervalWeeks: 16,
  },
  {
    code: 'INSULIN', name: 'Fasting Insulin', shortName: 'Insulin',
    category: 'GLUCOSE_INSULIN', unit: 'µIU/mL',
    longevityOptimalLow: 2, longevityOptimalHigh: 5,
    populationAvgLow: 2, populationAvgHigh: 25,
    bryanJohnsonValue: 3.2,
    description: 'The earliest marker of insulin resistance — appears BEFORE glucose rises. Peter Attia considers this the most important metabolic marker. If elevated, metabolic dysfunction is already present even with normal glucose.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: [] },
    interventionsIfHigh: {
      lifestyle: ['Time-restricted eating (16:8 minimum)', 'HIIT + strength training', 'Walk 30 min after every meal', 'Reduce carbs, increase protein and fiber'],
      supplements: [
        { name: 'Berberine', dose: '500mg 2x/day with meals', priority: 'MUST' },
        { name: 'Magnesium glycinate', dose: '400mg evening', priority: 'STRONG' },
        { name: 'Chromium picolinate', dose: '200mcg daily', priority: 'OPTIONAL' },
      ],
      foods_add: ['Apple cider vinegar before meals', 'Cinnamon', 'Fiber-rich foods', 'Protein at every meal'],
      foods_avoid: ['Simple carbs', 'Juice', 'Processed cereals', 'Snacking between meals'],
      medical: ['Calculate HOMA-IR', 'Discuss metformin if >10', 'CGM recommended'],
    },
    retestIntervalWeeks: 12,
  },

  // ══════ LIPIDS ══════
  {
    code: 'LDL', name: 'LDL Cholesterol', shortName: 'LDL-C',
    category: 'LIPIDS', unit: 'mg/dL',
    longevityOptimalLow: 50, longevityOptimalHigh: 100,
    populationAvgLow: 100, populationAvgHigh: 160,
    bryanJohnsonValue: 53,
    description: 'Oxidized LDL penetrates arterial walls causing atherosclerosis. ApoB is more precise, but LDL remains essential. Bryan achieves 53 with Repatha (PCSK9 inhibitor). For most people, <100 via lifestyle is the target.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: ['Check liver function if <40'] },
    interventionsIfHigh: {
      lifestyle: ['Plant-heavy diet', 'Aerobic exercise 150+ min/week', 'Reduce saturated fat', 'Increase soluble fiber'],
      supplements: [
        { name: 'Psyllium fiber', dose: '5-10g daily', priority: 'MUST' },
        { name: 'Citrus bergamot', dose: '500mg 2x/day', priority: 'STRONG' },
        { name: 'Plant sterols', dose: '2g daily', priority: 'OPTIONAL' },
      ],
      foods_add: ['Oats', 'Nuts', 'Legumes', 'Olive oil', 'Avocado'],
      foods_avoid: ['Excess butter', 'Frequent red meat', 'Full-fat cheese', 'Coconut oil in excess'],
      medical: ['Discuss statin if >160 or high CV risk', 'Get ApoB test for precision', 'Coronary calcium score if >130 + other risk factors'],
    },
    retestIntervalWeeks: 12,
  },
  {
    code: 'HDL', name: 'HDL Cholesterol', shortName: 'HDL-C',
    category: 'LIPIDS', unit: 'mg/dL',
    longevityOptimalLow: 55, longevityOptimalHigh: 90,
    populationAvgLow: 40, populationAvgHigh: 60,
    bryanJohnsonValue: 67,
    description: '"Good" cholesterol — transports cholesterol back to liver. Exercise is the #1 HDL raiser. Low HDL combined with high triglycerides = metabolic dysfunction signal.',
    interventionsIfLow: {
      lifestyle: ['Exercise regularly (biggest HDL raiser: 5-10%)', 'Reduce refined carbs', 'Add healthy fats'],
      supplements: [{ name: 'Niacin (B3)', dose: '500mg daily', priority: 'OPTIONAL' }],
      foods_add: ['Fatty fish', 'Olive oil', 'Avocado', 'Nuts', 'Dark chocolate >85%'],
      foods_avoid: ['Trans fats', 'Refined sugar', 'Seed oils'],
      medical: ['Check metabolic syndrome criteria', 'Calculate TG/HDL ratio'],
    },
    interventionsIfHigh: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: ['Very high HDL (>100) may be dysfunctional — check HDL function'] },
    retestIntervalWeeks: 12,
  },
  {
    code: 'TRIG', name: 'Triglycerides', shortName: 'Triglycerides',
    category: 'LIPIDS', unit: 'mg/dL',
    longevityOptimalLow: 30, longevityOptimalHigh: 80,
    populationAvgLow: 80, populationAvgHigh: 150,
    bryanJohnsonValue: 44,
    description: 'Reflects carb metabolism and insulin resistance. TG/HDL ratio <1.5 is ideal (surrogate for insulin sensitivity). The best lifestyle-responsive lipid marker.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: [] },
    interventionsIfHigh: {
      lifestyle: ['Eliminate alcohol', 'Reduce refined carbs dramatically', 'Daily exercise', 'Time-restricted eating'],
      supplements: [
        { name: 'Omega-3 EPA/DHA', dose: '2-4g daily', priority: 'MUST' },
        { name: 'Berberine', dose: '500mg 2x/day', priority: 'STRONG' },
      ],
      foods_add: ['Fatty fish', 'Nuts', 'Flaxseeds', 'Olive oil'],
      foods_avoid: ['Alcohol (top TG driver)', 'Fruit juice', 'White bread', 'White rice', 'Sugary drinks'],
      medical: ['Check insulin resistance', 'Extended lipid panel', 'If >500: URGENT — pancreatitis risk'],
    },
    retestIntervalWeeks: 8,
  },
  {
    code: 'APOB', name: 'Apolipoprotein B', shortName: 'ApoB',
    category: 'LIPIDS', unit: 'mg/dL',
    longevityOptimalLow: 40, longevityOptimalHigh: 80,
    populationAvgLow: 60, populationAvgHigh: 130,
    bryanJohnsonValue: 40,
    description: 'The single best predictor of cardiovascular risk — counts every atherogenic particle. Peter Attia considers this THE lipid marker to optimize. More predictive than LDL-C.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: [] },
    interventionsIfHigh: {
      lifestyle: ['Same as LDL interventions but more aggressive', 'Mediterranean diet pattern'],
      supplements: [
        { name: 'Psyllium fiber', dose: '10g daily', priority: 'MUST' },
        { name: 'Citrus bergamot', dose: '1000mg daily', priority: 'STRONG' },
      ],
      foods_add: ['Oats', 'Legumes', 'Nuts', 'Olive oil'],
      foods_avoid: ['Saturated fat >20g/day', 'Trans fats completely'],
      medical: ['Discuss statin if >90 with risk factors', 'Coronary calcium score recommended'],
    },
    retestIntervalWeeks: 12,
  },

  // ══════ THYROID ══════
  {
    code: 'TSH', name: 'Thyroid Stimulating Hormone', shortName: 'TSH',
    category: 'THYROID', unit: 'mIU/L',
    longevityOptimalLow: 0.5, longevityOptimalHigh: 2.0,
    populationAvgLow: 0.4, populationAvgHigh: 4.0,
    bryanJohnsonValue: 1.4,
    description: 'Even within "normal" range, TSH >2.5 may indicate subclinical hypothyroidism. Thyroid affects metabolism, energy, weight, mood, cognition, and heart rate. Bryan takes both levothyroxine and Armour Thyroid.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: ['URGENT: Check hyperthyroidism', 'Test FT3, FT4, antibodies'] },
    interventionsIfHigh: {
      lifestyle: ['Stress management', 'Adequate sleep', 'Moderate exercise (not excessive)'],
      supplements: [
        { name: 'Selenium', dose: '200mcg daily', priority: 'STRONG' },
        { name: 'Zinc', dose: '25mg daily', priority: 'STRONG' },
        { name: 'Iodine', dose: '150mcg daily (if deficient)', priority: 'OPTIONAL' },
      ],
      foods_add: ['Brazil nuts (selenium)', 'Seafood (iodine)', 'Eggs'],
      foods_avoid: ['Excessive raw cruciferous if hypothyroid', 'Excess soy'],
      medical: ['Endocrinologist if >4.0', 'Full panel: FT3, FT4, anti-TPO, anti-TG'],
    },
    retestIntervalWeeks: 8,
  },
  {
    code: 'FT4', name: 'Free Thyroxine', shortName: 'Free T4',
    category: 'THYROID', unit: 'ng/dL',
    longevityOptimalLow: 1.0, longevityOptimalHigh: 1.5,
    populationAvgLow: 0.8, populationAvgHigh: 1.8,
    bryanJohnsonValue: undefined,
    description: 'Active thyroid hormone precursor. Combined with TSH, gives a complete picture of thyroid function. Low FT4 + high TSH = primary hypothyroidism.',
    interventionsIfLow: {
      lifestyle: ['Ensure adequate iodine intake', 'Stress management'],
      supplements: [{ name: 'Selenium', dose: '200mcg daily', priority: 'STRONG' }],
      foods_add: ['Seafood', 'Iodized salt', 'Eggs'],
      foods_avoid: [],
      medical: ['Endocrinologist referral', 'Check anti-TPO antibodies'],
    },
    interventionsIfHigh: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: ['Rule out hyperthyroidism', 'Check TSH'] },
    retestIntervalWeeks: 8,
  },
  {
    code: 'ANTI_TPO', name: 'Anti-Thyroid Peroxidase Antibodies', shortName: 'Anti-TPO',
    category: 'THYROID', unit: 'IU/mL',
    longevityOptimalLow: 0, longevityOptimalHigh: 9,
    populationAvgLow: 0, populationAvgHigh: 34,
    bryanJohnsonValue: undefined,
    description: 'Elevated anti-TPO indicates autoimmune thyroiditis (Hashimoto\'s). Present in ~10% of women and ~3% of men. Early detection allows proactive management.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: [] },
    interventionsIfHigh: {
      lifestyle: ['Gluten-free trial 3 months', 'Stress reduction', 'Adequate sleep', 'Anti-inflammatory diet'],
      supplements: [
        { name: 'Selenium', dose: '200mcg daily', priority: 'MUST' },
        { name: 'Vitamin D3', dose: '4000 IU daily', priority: 'STRONG' },
      ],
      foods_add: ['Anti-inflammatory foods', 'Omega-3 rich fish'],
      foods_avoid: ['Gluten (trial)', 'Excess iodine', 'Processed food'],
      medical: ['Endocrinologist mandatory', 'Monitor TSH every 6 months', 'Ultrasound thyroid'],
    },
    retestIntervalWeeks: 24,
  },

  // ══════ HORMONES ══════
  {
    code: 'TESTO', name: 'Total Testosterone', shortName: 'Testosterone',
    category: 'HORMONES', unit: 'ng/dL',
    longevityOptimalLow: 500, longevityOptimalHigh: 900,
    populationAvgLow: 300, populationAvgHigh: 1000,
    bryanJohnsonValue: 750,
    description: 'Key anabolic hormone. Declines 1-2%/year after 30. Impacts muscle mass, bone density, energy, cognition, mood, and body composition. Bryan achieves 941 ng/dL naturally at 47.',
    interventionsIfLow: {
      lifestyle: ['Sleep 7-9 hours (biggest lever)', 'Heavy strength training 3x/week', 'Reduce body fat to 10-18%', 'Manage stress (cortisol suppresses T)', 'Eliminate alcohol'],
      supplements: [
        { name: 'Zinc', dose: '30mg daily', priority: 'MUST' },
        { name: 'Vitamin D3', dose: '4000 IU daily', priority: 'STRONG' },
        { name: 'Ashwagandha KSM-66', dose: '600mg daily', priority: 'STRONG' },
        { name: 'Magnesium', dose: '400mg evening', priority: 'STRONG' },
      ],
      foods_add: ['Eggs', 'Oysters (zinc)', 'Brazil nuts (selenium)', 'Pomegranate'],
      foods_avoid: ['Alcohol', 'Processed soy', 'Mint/spearmint tea', 'BPA plastics'],
      medical: ['Endocrinologist if <300 ng/dL', 'Check SHBG, LH, FSH, prolactin, estradiol'],
    },
    interventionsIfHigh: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: ['Verify source if >1100 without TRT'] },
    retestIntervalWeeks: 12,
    sexSpecific: true,
  },
  {
    code: 'ESTRADIOL', name: 'Estradiol (E2)', shortName: 'Estradiol',
    category: 'HORMONES', unit: 'pg/mL',
    longevityOptimalLow: 20, longevityOptimalHigh: 40,
    populationAvgLow: 10, populationAvgHigh: 50,
    bryanJohnsonValue: undefined,
    description: 'Important for both sexes. In men, too low = joint pain, bone loss; too high = gynecomastia, water retention. In women (premenopausal), varies with cycle.',
    interventionsIfLow: {
      lifestyle: ['Moderate exercise', 'Adequate body fat (not too lean)'],
      supplements: [{ name: 'DHEA', dose: '25mg daily (discuss with doctor)', priority: 'OPTIONAL' }],
      foods_add: ['Flaxseeds', 'Soy (moderate)', 'Berries'],
      foods_avoid: [],
      medical: ['Check testosterone and SHBG', 'Bone density scan if chronically low'],
    },
    interventionsIfHigh: {
      lifestyle: ['Reduce body fat', 'Reduce alcohol', 'Increase fiber'],
      supplements: [{ name: 'DIM (Diindolylmethane)', dose: '200mg daily', priority: 'OPTIONAL' }],
      foods_add: ['Cruciferous vegetables (broccoli, cauliflower)', 'Fiber'],
      foods_avoid: ['Alcohol', 'Excess soy', 'Plastic containers (xenoestrogens)'],
      medical: ['Check liver function (estrogen clearance)'],
    },
    retestIntervalWeeks: 12,
    sexSpecific: true,
  },
  {
    code: 'CORTISOL', name: 'Morning Cortisol', shortName: 'Cortisol AM',
    category: 'HORMONES', unit: 'µg/dL',
    longevityOptimalLow: 10, longevityOptimalHigh: 18,
    populationAvgLow: 6, populationAvgHigh: 23,
    bryanJohnsonValue: undefined,
    description: 'Stress hormone. Should be highest in morning, lowest at night. Chronic elevation destroys muscle, weakens immunity, impairs sleep, raises blood sugar, and accelerates aging.',
    interventionsIfLow: {
      lifestyle: ['Evaluate adrenal fatigue', 'Gentle exercise only', 'Rest and recovery focus'],
      supplements: [{ name: 'Ashwagandha KSM-66', dose: '600mg morning', priority: 'STRONG' }],
      foods_add: ['Nutrient-dense foods', 'Regular meals'],
      foods_avoid: ['Fasting if cortisol is low'],
      medical: ['Endocrinologist — rule out adrenal insufficiency'],
    },
    interventionsIfHigh: {
      lifestyle: ['Meditation 10-20 min daily', 'Deep breathing exercises', 'Nature exposure', 'Reduce caffeine', 'Limit intense exercise to morning'],
      supplements: [
        { name: 'Ashwagandha KSM-66', dose: '600mg evening', priority: 'MUST' },
        { name: 'Magnesium glycinate', dose: '400mg evening', priority: 'STRONG' },
        { name: 'L-Theanine', dose: '200mg as needed', priority: 'OPTIONAL' },
      ],
      foods_add: ['Dark chocolate', 'Green tea', 'Chamomile tea'],
      foods_avoid: ['Caffeine after noon', 'Alcohol', 'Late-night eating'],
      medical: ['Check 4-point cortisol (saliva) for diurnal pattern', 'Rule out Cushing\'s if very high'],
    },
    retestIntervalWeeks: 8,
  },
  {
    code: 'DHEAS', name: 'DHEA-Sulfate', shortName: 'DHEA-S',
    category: 'HORMONES', unit: 'µg/dL',
    longevityOptimalLow: 200, longevityOptimalHigh: 400,
    populationAvgLow: 100, populationAvgHigh: 500,
    bryanJohnsonValue: undefined,
    description: 'DHEA is the most abundant hormone in the body and a precursor to sex hormones. Declines steadily with age. Low DHEA-S is associated with accelerated aging, cardiovascular disease, and cognitive decline.',
    interventionsIfLow: {
      lifestyle: ['Strength training', 'Stress management', 'Adequate sleep'],
      supplements: [{ name: 'DHEA', dose: '25-50mg daily (discuss with doctor)', priority: 'OPTIONAL' }],
      foods_add: ['Wild yam', 'Healthy fats'],
      foods_avoid: [],
      medical: ['Check adrenal function', 'Monitor if supplementing'],
    },
    interventionsIfHigh: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: ['Check for adrenal tumor if very high'] },
    retestIntervalWeeks: 12,
    ageAdjusted: true,
  },

  // ══════ LIVER ══════
  {
    code: 'ALT', name: 'Alanine Aminotransferase', shortName: 'ALT (TGP)',
    category: 'LIVER', unit: 'U/L',
    longevityOptimalLow: 10, longevityOptimalHigh: 25,
    populationAvgLow: 10, populationAvgHigh: 40,
    bryanJohnsonValue: 16,
    description: 'Primary liver health marker. Elevated ALT indicates liver inflammation — most commonly from non-alcoholic fatty liver disease (NAFLD), which affects 25% of adults.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: [] },
    interventionsIfHigh: {
      lifestyle: ['Eliminate alcohol', 'Lose weight if overweight', 'Exercise regularly', 'Reduce fructose'],
      supplements: [
        { name: 'NAC (N-Acetylcysteine)', dose: '1200mg daily', priority: 'STRONG' },
        { name: 'Milk Thistle (Silymarin)', dose: '300mg daily', priority: 'OPTIONAL' },
      ],
      foods_add: ['Broccoli', 'Cabbage', 'Green tea', 'Artichoke'],
      foods_avoid: ['Alcohol', 'Excess fructose', 'Fried food', 'Acetaminophen'],
      medical: ['Liver ultrasound if >40', 'Check hepatitis B/C', 'GGT for alcohol marker'],
    },
    retestIntervalWeeks: 8,
  },
  {
    code: 'AST', name: 'Aspartate Aminotransferase', shortName: 'AST (TGO)',
    category: 'LIVER', unit: 'U/L',
    longevityOptimalLow: 10, longevityOptimalHigh: 25,
    populationAvgLow: 10, populationAvgHigh: 40,
    bryanJohnsonValue: 13,
    description: 'Liver and muscle enzyme. AST/ALT ratio >2 suggests alcoholic liver disease. Can also be elevated from intense exercise (muscle breakdown).',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: [] },
    interventionsIfHigh: {
      lifestyle: ['Same as ALT interventions', 'If exercising intensely, retest after 3 rest days'],
      supplements: [{ name: 'NAC', dose: '1200mg daily', priority: 'STRONG' }],
      foods_add: ['Liver-protective foods: turmeric, garlic, leafy greens'],
      foods_avoid: ['Alcohol', 'Acetaminophen'],
      medical: ['If both ALT+AST >40: comprehensive liver workup', 'Check AST/ALT ratio'],
    },
    retestIntervalWeeks: 8,
  },
  {
    code: 'GGT', name: 'Gamma-Glutamyl Transferase', shortName: 'GGT',
    category: 'LIVER', unit: 'U/L',
    longevityOptimalLow: 10, longevityOptimalHigh: 25,
    populationAvgLow: 10, populationAvgHigh: 60,
    bryanJohnsonValue: undefined,
    description: 'Sensitive marker for liver stress and alcohol use. Also an independent marker of oxidative stress and cardiovascular risk. Very responsive to alcohol elimination.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: [] },
    interventionsIfHigh: {
      lifestyle: ['Eliminate alcohol completely for 30 days', 'Weight loss if overweight', 'Exercise'],
      supplements: [{ name: 'NAC', dose: '1200mg daily', priority: 'STRONG' }],
      foods_add: ['Coffee (protective for liver)', 'Green tea', 'Cruciferous vegetables'],
      foods_avoid: ['Alcohol (#1 cause)', 'Acetaminophen', 'Processed food'],
      medical: ['If >100: liver ultrasound', 'Check hepatitis panel'],
    },
    retestIntervalWeeks: 8,
  },

  // ══════ KIDNEY ══════
  {
    code: 'CREAT', name: 'Creatinine', shortName: 'Creatinine',
    category: 'KIDNEY', unit: 'mg/dL',
    longevityOptimalLow: 0.7, longevityOptimalHigh: 1.1,
    populationAvgLow: 0.6, populationAvgHigh: 1.2,
    bryanJohnsonValue: 0.93,
    description: 'Primary kidney function marker. eGFR is calculated from creatinine. Can be elevated by creatine supplementation or high muscle mass — context matters.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: ['May indicate low muscle mass'] },
    interventionsIfHigh: {
      lifestyle: ['Hydrate adequately (2-3L/day)', 'Stop creatine supplementation temporarily for accurate reading'],
      supplements: [],
      foods_add: ['Water', 'Water-rich fruits'],
      foods_avoid: ['Creatine supplements if eGFR is low'],
      medical: ['URGENT: Nephrologist if >1.5 or eGFR <60', 'Check Cystatin-C for confirmation', 'Renal ultrasound'],
    },
    retestIntervalWeeks: 12,
  },
  {
    code: 'URIC_ACID', name: 'Uric Acid', shortName: 'Uric Acid',
    category: 'KIDNEY', unit: 'mg/dL',
    longevityOptimalLow: 3.5, longevityOptimalHigh: 5.5,
    populationAvgLow: 3.5, populationAvgHigh: 7.2,
    bryanJohnsonValue: undefined,
    description: 'Elevated uric acid causes gout, kidney stones, and is linked to metabolic syndrome, hypertension, and cardiovascular disease. Also a marker of fructose overconsumption.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: [] },
    interventionsIfHigh: {
      lifestyle: ['Hydrate aggressively (3L/day)', 'Reduce purine-rich foods', 'Eliminate alcohol (especially beer)', 'Reduce fructose'],
      supplements: [{ name: 'Vitamin C', dose: '500mg daily', priority: 'STRONG' }],
      foods_add: ['Cherries (tart cherry juice)', 'Water', 'Low-fat dairy'],
      foods_avoid: ['Beer', 'Organ meats', 'Shellfish', 'High-fructose corn syrup', 'Sugary drinks'],
      medical: ['Rheumatologist if >9.0 or gout history', 'Discuss allopurinol if >8.0', 'Check kidney function'],
    },
    retestIntervalWeeks: 8,
  },

  // ══════ VITAMINS ══════
  {
    code: 'VITD', name: '25-Hydroxyvitamin D', shortName: 'Vitamin D',
    category: 'VITAMINS', unit: 'ng/mL',
    longevityOptimalLow: 50, longevityOptimalHigh: 80,
    populationAvgLow: 20, populationAvgHigh: 40,
    bryanJohnsonValue: 72,
    description: 'Steroid hormone essential for 1000+ genes. 70% of Europeans are deficient. Impacts: immunity, bones, mood, cancer prevention, cardiovascular health, longevity. The most common deficiency worldwide.',
    interventionsIfLow: {
      lifestyle: ['Sun exposure 15-30 min/day (when UV index >3)', 'Take with fatty meal for absorption'],
      supplements: [
        { name: 'Vitamin D3', dose: '4000-5000 IU daily', priority: 'MUST' },
        { name: 'Vitamin K2-MK7', dose: '200mcg daily', priority: 'MUST' },
      ],
      foods_add: ['Fatty fish', 'UV-exposed mushrooms', 'Eggs', 'Fortified foods'],
      foods_avoid: [],
      medical: ['Retest at 12 weeks', 'Check calcium and PTH', 'If <20: loading dose 10,000 IU/day for 8 weeks'],
    },
    interventionsIfHigh: { lifestyle: ['Reduce supplementation'], supplements: [], foods_add: [], foods_avoid: [], medical: ['Check serum calcium if >100'] },
    retestIntervalWeeks: 12,
  },
  {
    code: 'B12', name: 'Vitamin B12', shortName: 'B12',
    category: 'VITAMINS', unit: 'pg/mL',
    longevityOptimalLow: 500, longevityOptimalHigh: 1000,
    populationAvgLow: 200, populationAvgHigh: 900,
    bryanJohnsonValue: 680,
    description: 'Essential for nerve function, DNA synthesis, and energy. Deficiency is common in vegetarians/vegans (no plant sources) and elderly (reduced absorption). Deficiency causes irreversible nerve damage if prolonged.',
    interventionsIfLow: {
      lifestyle: [],
      supplements: [{ name: 'Methylcobalamin B12', dose: '1000mcg sublingual daily', priority: 'MUST' }],
      foods_add: ['Liver', 'Sardines', 'Eggs', 'Nutritional yeast (fortified)'],
      foods_avoid: [],
      medical: ['Check homocysteine and MMA (methylmalonic acid)', 'Intrinsic factor antibodies if very low'],
    },
    interventionsIfHigh: { lifestyle: ['Reduce B12 supplementation'], supplements: [], foods_add: [], foods_avoid: [], medical: ['Very high B12 can indicate liver problems'] },
    retestIntervalWeeks: 12,
  },
  {
    code: 'FOLAT', name: 'Serum Folate', shortName: 'Folate',
    category: 'VITAMINS', unit: 'ng/mL',
    longevityOptimalLow: 15, longevityOptimalHigh: 40,
    populationAvgLow: 3, populationAvgHigh: 20,
    bryanJohnsonValue: 28,
    description: 'Essential for methylation, DNA synthesis, and homocysteine conversion. Deficiency increases cardiovascular and cognitive risk. MTHFR variants affect folate metabolism in ~40% of population.',
    interventionsIfLow: {
      lifestyle: [],
      supplements: [{ name: 'Methylfolate (5-MTHF)', dose: '400-800mcg daily', priority: 'MUST' }],
      foods_add: ['Spinach', 'Lentils', 'Asparagus', 'Broccoli', 'Avocado'],
      foods_avoid: [],
      medical: ['Test MTHFR C677T', 'Check homocysteine and B12'],
    },
    interventionsIfHigh: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: [] },
    retestIntervalWeeks: 12,
  },

  // ══════ MINERALS ══════
  {
    code: 'FERRITIN', name: 'Ferritin', shortName: 'Ferritin',
    category: 'MINERALS', unit: 'ng/mL',
    longevityOptimalLow: 40, longevityOptimalHigh: 100,
    populationAvgLow: 30, populationAvgHigh: 300,
    bryanJohnsonValue: 54,
    description: 'Iron storage. Too low = anemia, fatigue. Too high = oxidative stress, accelerated aging. Bryan donates blood regularly to keep ferritin optimal. Iron overload is an underappreciated aging accelerator.',
    interventionsIfLow: {
      lifestyle: ['Pair iron-rich foods with vitamin C', 'Avoid tea/coffee with meals'],
      supplements: [{ name: 'Iron bisglycinate', dose: '25-50mg daily', priority: 'MUST' }],
      foods_add: ['Red meat', 'Spinach', 'Lentils', 'Pumpkin seeds'],
      foods_avoid: ['Tea/coffee at meals (inhibits absorption)'],
      medical: ['Investigate cause: blood loss, malabsorption, heavy periods'],
    },
    interventionsIfHigh: {
      lifestyle: ['Donate blood every 3 months', 'Reduce red meat'],
      supplements: [],
      foods_add: ['Green tea (mild chelator)'],
      foods_avoid: ['Iron supplements', 'Frequent red meat', 'Vitamin C supplements with meals'],
      medical: ['HFE genetic test for hemochromatosis if >300', 'Liver function tests'],
    },
    retestIntervalWeeks: 12,
  },
  {
    code: 'MAGNE', name: 'Serum Magnesium', shortName: 'Magnesium',
    category: 'MINERALS', unit: 'mg/dL',
    longevityOptimalLow: 2.0, longevityOptimalHigh: 2.4,
    populationAvgLow: 1.7, populationAvgHigh: 2.2,
    bryanJohnsonValue: 2.2,
    description: 'Cofactor in 300+ enzymatic reactions. 50% of population is deficient. Serum reflects only 1% of total body magnesium — so even "normal" serum may mask deficiency. Affects sleep, stress, muscles, bones, glucose.',
    interventionsIfLow: {
      lifestyle: ['Epsom salt baths', 'Reduce stress', 'Reduce alcohol and caffeine'],
      supplements: [{ name: 'Magnesium glycinate', dose: '400mg evening', priority: 'MUST' }],
      foods_add: ['Dark chocolate >85%', 'Pumpkin seeds', 'Avocado', 'Spinach', 'Almonds'],
      foods_avoid: ['Excess alcohol', 'Excess caffeine', 'Processed food'],
      medical: ['RBC magnesium test (more accurate than serum)'],
    },
    interventionsIfHigh: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: ['Check kidney function'] },
    retestIntervalWeeks: 12,
  },
  {
    code: 'IRON', name: 'Serum Iron', shortName: 'Iron',
    category: 'MINERALS', unit: 'µg/dL',
    longevityOptimalLow: 60, longevityOptimalHigh: 120,
    populationAvgLow: 60, populationAvgHigh: 170,
    bryanJohnsonValue: undefined,
    description: 'Serum iron combined with ferritin and TIBC gives a complete iron picture. Both deficiency and overload are harmful. Must be interpreted alongside ferritin.',
    interventionsIfLow: {
      lifestyle: ['Pair iron-rich foods with vitamin C'],
      supplements: [{ name: 'Iron bisglycinate', dose: '25mg daily', priority: 'MUST' }],
      foods_add: ['Liver', 'Red meat', 'Spinach', 'Lentils'],
      foods_avoid: ['Tea/coffee with iron-rich meals'],
      medical: ['Check ferritin, TIBC, transferrin saturation'],
    },
    interventionsIfHigh: {
      lifestyle: ['Blood donation'],
      supplements: [],
      foods_add: [],
      foods_avoid: ['Iron supplements'],
      medical: ['Check ferritin and transferrin saturation', 'Rule out hemochromatosis'],
    },
    retestIntervalWeeks: 12,
  },

  // ══════ BLOOD COUNT ══════
  {
    code: 'WBC', name: 'White Blood Cells', shortName: 'WBC',
    category: 'BLOOD_COUNT', unit: '×10³/µL',
    longevityOptimalLow: 4.0, longevityOptimalHigh: 6.0,
    populationAvgLow: 4.5, populationAvgHigh: 11.0,
    bryanJohnsonValue: 4.7,
    description: 'Elevated WBC (even within "normal") indicates chronic inflammation. WBC <6.0 is associated with increased longevity. Below 4.0 needs investigation.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: ['Investigate if <3.5 — possible immune issue'] },
    interventionsIfHigh: {
      lifestyle: ['Anti-inflammatory exercise', 'Adequate sleep', 'Stress management'],
      supplements: [{ name: 'Omega-3', dose: '2g daily', priority: 'STRONG' }],
      foods_add: ['Turmeric', 'Ginger', 'Green tea', 'Berries'],
      foods_avoid: ['Processed food', 'Sugar', 'Alcohol'],
      medical: ['Rule out infection if >11', 'Check differential (neutrophils, lymphocytes, etc.)'],
    },
    retestIntervalWeeks: 8,
  },
  {
    code: 'HGB', name: 'Hemoglobin', shortName: 'Hemoglobin',
    category: 'BLOOD_COUNT', unit: 'g/dL',
    longevityOptimalLow: 13.5, longevityOptimalHigh: 15.5,
    populationAvgLow: 12.0, populationAvgHigh: 17.0,
    bryanJohnsonValue: 14.8,
    description: 'Oxygen carrying capacity. Low = anemia, fatigue. High = dehydration or polycythemia. Directly impacts energy, exercise performance, and cognitive function.',
    interventionsIfLow: {
      lifestyle: ['Iron-rich meals with vitamin C'],
      supplements: [{ name: 'Iron bisglycinate', dose: '25mg daily', priority: 'MUST' }],
      foods_add: ['Red meat', 'Spinach', 'Lentils', 'Beetroot'],
      foods_avoid: ['Coffee/tea at meals'],
      medical: ['Investigate anemia cause: iron, B12, folate, chronic disease, bleeding'],
    },
    interventionsIfHigh: { lifestyle: ['Hydrate', 'Blood donation'], supplements: [], foods_add: [], foods_avoid: [], medical: ['Check polycythemia if >17 (male) or >15 (female)'] },
    retestIntervalWeeks: 12,
  },
  {
    code: 'PLT', name: 'Platelets', shortName: 'Platelets',
    category: 'BLOOD_COUNT', unit: '×10³/µL',
    longevityOptimalLow: 150, longevityOptimalHigh: 300,
    populationAvgLow: 150, populationAvgHigh: 400,
    bryanJohnsonValue: undefined,
    description: 'Blood clotting cells. Too low = bleeding risk. Too high = clotting risk. Also a marker of inflammation and bone marrow function.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: ['URGENT if <100: hematologist referral'] },
    interventionsIfHigh: {
      lifestyle: ['Anti-inflammatory diet', 'Exercise'],
      supplements: [{ name: 'Omega-3', dose: '2g daily (mild anti-platelet effect)', priority: 'OPTIONAL' }],
      foods_add: ['Turmeric', 'Garlic', 'Ginger'],
      foods_avoid: [],
      medical: ['Rule out reactive thrombocytosis if >400', 'Check iron status and inflammation'],
    },
    retestIntervalWeeks: 12,
  },
  {
    code: 'RBC', name: 'Red Blood Cells', shortName: 'RBC',
    category: 'BLOOD_COUNT', unit: '×10⁶/µL',
    longevityOptimalLow: 4.5, longevityOptimalHigh: 5.5,
    populationAvgLow: 4.2, populationAvgHigh: 5.9,
    bryanJohnsonValue: undefined,
    description: 'Red blood cell count. Complements hemoglobin in assessing oxygen-carrying capacity and anemia.',
    interventionsIfLow: {
      lifestyle: [],
      supplements: [{ name: 'Iron bisglycinate', dose: '25mg daily if iron-deficient', priority: 'STRONG' }],
      foods_add: ['Iron-rich foods'],
      foods_avoid: [],
      medical: ['Complete anemia workup: iron, B12, folate, reticulocytes'],
    },
    interventionsIfHigh: { lifestyle: ['Hydrate'], supplements: [], foods_add: [], foods_avoid: [], medical: ['Check for polycythemia vera if >6.0'] },
    retestIntervalWeeks: 12,
  },

  // ══════ METABOLIC + CBC DETAIL (for full PhenoAge coverage) ══════
  // The next 5 markers unlock PhenoAge's 9/9 signal. Without them the
  // biological-age estimator fills gaps with population averages, pulling
  // results toward the mean. A CBC + CMP panel from any primary-care order
  // covers all five.
  {
    code: 'ALBUMIN', name: 'Serum Albumin', shortName: 'Albumin',
    category: 'LIVER', unit: 'g/dL',
    longevityOptimalLow: 4.4, longevityOptimalHigh: 5.0,
    populationAvgLow: 3.5, populationAvgHigh: 5.2,
    bryanJohnsonValue: 4.7,
    description: 'Primary blood protein, synthesized by liver. Reflects nutritional status, liver function, and inflammation. Declining albumin is one of the strongest blood predictors of all-cause mortality. PhenoAge input.',
    interventionsIfLow: {
      lifestyle: ['Increase protein intake to 1.6-2.0 g/kg bodyweight', 'Resistance training'],
      supplements: [{ name: 'Whey / pea protein', dose: '25-40g post-workout', priority: 'STRONG' }],
      foods_add: ['Eggs', 'Fish', 'Legumes', 'Lean meats'],
      foods_avoid: [],
      medical: ['Investigate liver function (synthesis)', 'Rule out kidney loss (proteinuria)', 'Check chronic inflammation'],
    },
    interventionsIfHigh: { lifestyle: ['Hydrate'], supplements: [], foods_add: [], foods_avoid: [], medical: ['Usually dehydration — re-test after rehydration'] },
    retestIntervalWeeks: 12,
  },
  {
    code: 'ALP', name: 'Alkaline Phosphatase', shortName: 'ALP',
    category: 'LIVER', unit: 'U/L',
    longevityOptimalLow: 40, longevityOptimalHigh: 70,
    populationAvgLow: 30, populationAvgHigh: 120,
    bryanJohnsonValue: 55,
    description: 'Enzyme from liver, bone, and intestine. Elevated ALP signals bile duct obstruction, bone turnover, or vitamin D deficiency. PhenoAge input — elevated ALP tracks accelerated aging.',
    interventionsIfLow: {
      lifestyle: [],
      supplements: [
        { name: 'Zinc', dose: '15-30mg daily', priority: 'OPTIONAL' },
        { name: 'Magnesium', dose: '400mg evening', priority: 'OPTIONAL' },
      ],
      foods_add: ['Leafy greens', 'Nuts'],
      foods_avoid: [],
      medical: ['Investigate zinc / magnesium deficiency if persistently <30'],
    },
    interventionsIfHigh: {
      lifestyle: ['Weight-bearing exercise (if bone source)'],
      supplements: [{ name: 'Vitamin D3', dose: '2000-4000 IU daily', priority: 'STRONG' }],
      foods_add: ['Vitamin D-rich foods: fatty fish, eggs'],
      foods_avoid: ['Alcohol'],
      medical: ['Fractionate (bone vs liver) if persistently >120', 'Check GGT — if normal, likely bone source'],
    },
    retestIntervalWeeks: 12,
  },
  {
    code: 'MCV', name: 'Mean Corpuscular Volume', shortName: 'MCV',
    category: 'BLOOD_COUNT', unit: 'fL',
    longevityOptimalLow: 85, longevityOptimalHigh: 92,
    populationAvgLow: 80, populationAvgHigh: 100,
    bryanJohnsonValue: 88,
    description: 'Average red blood cell size. Elevated = macrocytic (often B12 / folate deficiency, alcohol, hypothyroidism). Low = microcytic (iron deficiency, thalassemia). PhenoAge input.',
    interventionsIfLow: {
      lifestyle: [],
      supplements: [{ name: 'Iron bisglycinate', dose: '25mg daily', priority: 'STRONG' }],
      foods_add: ['Red meat', 'Lentils', 'Spinach'],
      foods_avoid: ['Coffee / tea at meals'],
      medical: ['Full iron panel: ferritin, TIBC, transferrin saturation'],
    },
    interventionsIfHigh: {
      lifestyle: ['Eliminate alcohol'],
      supplements: [
        { name: 'Vitamin B12 methylcobalamin', dose: '1000mcg daily', priority: 'STRONG' },
        { name: 'Folate (methylfolate)', dose: '400mcg daily', priority: 'STRONG' },
      ],
      foods_add: ['Leafy greens', 'Eggs', 'Fish'],
      foods_avoid: ['Alcohol'],
      medical: ['Check B12 + folate levels', 'Rule out hypothyroidism (TSH)', 'Investigate MDS if persistent + unexplained'],
    },
    retestIntervalWeeks: 12,
  },
  {
    code: 'RDW', name: 'Red Cell Distribution Width', shortName: 'RDW',
    category: 'BLOOD_COUNT', unit: '%',
    longevityOptimalLow: 11.5, longevityOptimalHigh: 13.0,
    populationAvgLow: 11.5, populationAvgHigh: 14.5,
    bryanJohnsonValue: 12.3,
    description: 'Variation in red blood cell size. Elevated RDW is a robust independent predictor of all-cause mortality — possibly reflecting subclinical inflammation and nutritional stress. PhenoAge input.',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: ['Rare — no action needed'] },
    interventionsIfHigh: {
      lifestyle: ['Anti-inflammatory protocol', 'Consistent sleep'],
      supplements: [
        { name: 'Iron (if ferritin low)', dose: '25mg daily', priority: 'STRONG' },
        { name: 'B12', dose: '1000mcg daily', priority: 'STRONG' },
        { name: 'Folate', dose: '400mcg daily', priority: 'STRONG' },
      ],
      foods_add: ['Leafy greens', 'Iron-rich foods'],
      foods_avoid: ['Alcohol'],
      medical: ['Full anemia workup: iron, B12, folate, reticulocytes', 'Check for mixed deficiency'],
    },
    retestIntervalWeeks: 12,
  },
  {
    code: 'LYMPH_PCT', name: 'Lymphocyte Percentage', shortName: 'Lymph %',
    category: 'BLOOD_COUNT', unit: '%',
    longevityOptimalLow: 28, longevityOptimalHigh: 40,
    populationAvgLow: 20, populationAvgHigh: 45,
    bryanJohnsonValue: 33,
    description: 'Share of white blood cells that are lymphocytes. Low lymphocytes signal immune suppression (chronic stress, aging, steroids). PhenoAge input — higher = younger.',
    interventionsIfLow: {
      lifestyle: ['Stress management (cortisol suppresses lymphocytes)', 'Sleep optimization'],
      supplements: [
        { name: 'Vitamin D3', dose: '4000 IU daily', priority: 'STRONG' },
        { name: 'Zinc', dose: '15mg daily', priority: 'STRONG' },
      ],
      foods_add: ['Citrus', 'Berries', 'Leafy greens'],
      foods_avoid: ['Chronic alcohol'],
      medical: ['Check vitamin D + zinc status', 'Rule out chronic viral infection if <15%'],
    },
    interventionsIfHigh: {
      lifestyle: [],
      supplements: [],
      foods_add: [],
      foods_avoid: [],
      medical: ['Check for viral infection / EBV / CMV if >50%', 'Full differential if persistent'],
    },
    retestIntervalWeeks: 12,
  },

  // ══════ CARDIAC ADVANCED ══════
  {
    code: 'LPA', name: 'Lipoprotein(a)', shortName: 'Lp(a)',
    category: 'CARDIAC_ADVANCED', unit: 'nmol/L',
    longevityOptimalLow: 0, longevityOptimalHigh: 75,
    populationAvgLow: 10, populationAvgHigh: 150,
    bryanJohnsonValue: undefined,
    description: '90% genetically determined — the one lipid you cannot easily change. Elevated Lp(a) is an independent, causal cardiovascular risk factor. 20% of people have elevated levels. Only needs to be tested ONCE (genetic).',
    interventionsIfLow: { lifestyle: [], supplements: [], foods_add: [], foods_avoid: [], medical: [] },
    interventionsIfHigh: {
      lifestyle: ['Aggressively optimize ALL other CV risk factors (you cannot lower Lp(a) much)', 'Exercise regularly'],
      supplements: [
        { name: 'Omega-3 EPA/DHA', dose: '2-3g daily', priority: 'MUST' },
        { name: 'Niacin', dose: '1-2g daily (discuss with doctor)', priority: 'OPTIONAL' },
      ],
      foods_add: ['Anti-inflammatory diet'],
      foods_avoid: ['All pro-inflammatory foods'],
      medical: ['Cardiology referral if >125 nmol/L', 'Coronary calcium score', 'Discuss aspirin with doctor', 'New drugs (olpasiran, lepodisiran) in trials'],
    },
    retestIntervalWeeks: 0, // genetic — test once
  },
];

export function getBiomarkerRef(code: string): BiomarkerReference | undefined {
  return BIOMARKER_DB.find((b) => b.code === code);
}

export const BIOMARKER_CATEGORIES = [...new Set(BIOMARKER_DB.map((b) => b.category))];

// Category labels for UI
export const CATEGORY_LABELS: Record<string, string> = {
  INFLAMMATION: 'Inflammation',
  GLUCOSE_INSULIN: 'Glucose & Insulin',
  LIPIDS: 'Lipids',
  THYROID: 'Thyroid',
  HORMONES: 'Hormones',
  LIVER: 'Liver',
  KIDNEY: 'Kidney',
  VITAMINS: 'Vitamins',
  MINERALS: 'Minerals',
  BLOOD_COUNT: 'Blood Count',
  CARDIAC_ADVANCED: 'Advanced Cardiac',
};

// The "Big 11" — minimum biomarkers for a useful protocol
export const BIG_11_CODES = [
  'HBA1C', 'GLUC', 'INSULIN', 'LDL', 'HDL', 'TRIG',
  'HSCRP', 'VITD', 'TESTO', 'ALT', 'TSH',
];

// Extended panel — recommended for comprehensive protocol. Includes the
// 5 PhenoAge inputs (ALBUMIN, ALP, MCV, RDW, LYMPH_PCT) so a user who
// orders the extended panel gets 9/9 confidence on biological age.
export const EXTENDED_CODES = [
  ...BIG_11_CODES,
  'FERRITIN', 'B12', 'HOMOCYS', 'FOLAT', 'MAGNE',
  'WBC', 'HGB', 'OMEGA3', 'CREAT',
  'ALBUMIN', 'ALP', 'MCV', 'RDW', 'LYMPH_PCT',
];

// Full panel — everything we support
export const FULL_PANEL_CODES = BIOMARKER_DB.map(b => b.code);