// ============================================================================
// SAMPLE PROTOCOL — used by /dashboard?demo=1 for the landing page demo CTA.
// Profile: 35yo male, mediterranean eater, mild metabolic risk, gym access.
// Showcases every dashboard section without requiring sign-up.
// ============================================================================

import type { ProtocolOutput } from '@/lib/types';

export const SAMPLE_LONGEVITY_SCORE = 78;
export const SAMPLE_BIO_AGE = 32.4;

export const SAMPLE_PROTOCOL: ProtocolOutput = {
  diagnostic: {
    biologicalAge: 32.4,
    chronologicalAge: 35,
    agingVelocity: 'decelerated',
    agingVelocityNumber: 0.84,
    longevityScore: 78,
    summary: '35-year-old, ApoB elevated, hsCRP borderline, otherwise solid. Sleep + cardio routine is a strength. Highest leverage: drop ApoB via apoB-targeted nutrition + statin discussion.',
    topWins: [
      'Cardiovascular system 84/100 — top quartile for your age',
      'HDL 62 mg/dL — protective level, keep mediterranean pattern',
      'Sleep 7.6h with 78 sleep score — recovery is dialed',
      'Non-smoker — biggest single longevity factor',
    ],
    topRisks: [
      'ApoB 105 mg/dL — primary cardiovascular driver, target <80',
      'hsCRP 1.4 mg/L — borderline inflammation, target <1',
      'Sitting 9h/day — metabolic + postural risk, hourly walks needed',
      'VO2 Max 38 ml/kg/min — below optimal for age, build with Z2 cardio',
    ],
    organSystemScores: { cardiovascular: 84, metabolic: 72, hormonal: 76, inflammatory: 68, hepatic: 88, renal: 90, nutritional: 80, musculoskeletal: 75 },
    organSystemsDetailed: [
      { key: 'cardiovascular', label: 'Cardiovascular', description: 'Heart + vessels. Blood pressure, lipids, inflammation, cardio fitness.', score: 84, estimated: false, drivers: ['HDL 62 (protective)', 'BP 118/76', '180 min cardio/week'], improvers: ['Drop ApoB via dietary tweaks + statin discussion', 'Add 30 min Z2 cardio'] },
      { key: 'metabolic', label: 'Metabolic', description: 'Blood sugar + insulin sensitivity. How well your body handles carbs.', score: 72, estimated: false, drivers: ['HbA1c 5.4 (optimal)', '2x strength/week', 'Mediterranean diet'], improvers: ['Walk 10 min after dinner', 'Add berberine 500mg before largest carb meal'] },
      { key: 'inflammatory', label: 'Inflammatory', description: 'Chronic low-grade inflammation. The fire behind heart disease + dementia.', score: 68, estimated: false, drivers: ['hsCRP 1.4 (borderline)', '6 ultra-processed meals/week'], improvers: ['Omega-3 2g/day for 12 weeks', 'Curcumin 1g + black pepper'] },
      { key: 'hormonal', label: 'Hormonal', description: 'Thyroid, sex hormones, cortisol. Drives energy, libido, mood, body comp.', score: 76, estimated: true, drivers: ['Sleep adequate', 'Strength training 2x/week'], improvers: ['Sleep 8h on training days', 'Sunlight + magnesium evening'] },
      { key: 'hepatic', label: 'Hepatic', description: 'Liver function. Filters toxins, processes drugs, makes cholesterol.', score: 88, estimated: false, drivers: ['ALT 18 (optimal)', '4 drinks/week (moderate)'], improvers: ['Drop alcohol to <2/week for 4 weeks, retest'] },
      { key: 'renal', label: 'Renal', description: 'Kidney function. Filters blood, balances electrolytes, controls BP.', score: 90, estimated: false, drivers: ['Creatinine 0.91', 'Hydration 2.5L/day'], improvers: ['Maintain hydration', 'Limit NSAIDs'] },
      { key: 'nutritional', label: 'Nutritional', description: 'Vitamins, minerals, omega-3. The building blocks your cells need.', score: 80, estimated: false, drivers: ['Vitamin D 42 (optimal)', '5 servings veg/day'], improvers: ['Add fatty fish 2x/week', 'Brazil nuts 2/day for selenium'] },
      { key: 'musculoskeletal', label: 'Musculoskeletal', description: 'Muscle + bone + joints. Strength + mobility = functional longevity.', score: 75, estimated: true, drivers: ['Strength 2x/week', '8,200 avg steps/day'], improvers: ['Add 1 more strength day', '10k steps target'] },
    ],
    bryanSummary: { longevityScoreGap: -16, agingPaceGap: 0.20, bioAgePctDifference: 7.4, verdict: "Biologically 7.4% younger than chronological — solid head start.", keyGaps: [] },
    estimatedBiomarkers: [],
  },
  biomarkerReadout: [
    { code: 'HSCRP', name: 'High-Sensitivity C-Reactive Protein', shortName: 'hsCRP', value: 1.4, unit: 'mg/L', classification: 'SUBOPTIMAL_HIGH', longevityOptimalRange: [0, 1], labRange: [0, 3], bryanValue: 0.1, gap: 0.4 },
    { code: 'HBA1C', name: 'Glycated Hemoglobin', shortName: 'HbA1c', value: 5.4, unit: '%', classification: 'OPTIMAL', longevityOptimalRange: [4.6, 5.4], labRange: [4, 5.7], bryanValue: 4.5, gap: 0 },
    { code: 'LDL', name: 'LDL Cholesterol', shortName: 'LDL-C', value: 128, unit: 'mg/dL', classification: 'SUBOPTIMAL_HIGH', longevityOptimalRange: [50, 100], labRange: [0, 130], bryanValue: 45, gap: 28 },
    { code: 'HDL', name: 'HDL Cholesterol', shortName: 'HDL-C', value: 62, unit: 'mg/dL', classification: 'OPTIMAL', longevityOptimalRange: [55, 90], labRange: [40, 90], bryanValue: 78, gap: 0 },
    { code: 'TRIG', name: 'Triglycerides', shortName: 'Triglycerides', value: 88, unit: 'mg/dL', classification: 'OPTIMAL', longevityOptimalRange: [40, 100], labRange: [40, 150], bryanValue: 44, gap: 0 },
    { code: 'APOB', name: 'Apolipoprotein B', shortName: 'ApoB', value: 105, unit: 'mg/dL', classification: 'SUBOPTIMAL_HIGH', longevityOptimalRange: [50, 80], labRange: [50, 130], bryanValue: 50, gap: 25 },
    { code: 'VITD', name: 'Vitamin D 25-OH', shortName: 'Vitamin D', value: 42, unit: 'ng/mL', classification: 'OPTIMAL', longevityOptimalRange: [40, 80], labRange: [30, 100], bryanValue: 67.8, gap: 0 },
    { code: 'OMEGA3', name: 'Omega-3 Index', shortName: 'Omega-3 Index', value: 5.8, unit: '%', classification: 'SUBOPTIMAL_LOW', longevityOptimalRange: [8, 12], labRange: [4, 12], bryanValue: 9.98, gap: -2.2 },
    { code: 'ALT', name: 'Alanine Aminotransferase', shortName: 'ALT', value: 18, unit: 'U/L', classification: 'OPTIMAL', longevityOptimalRange: [10, 25], labRange: [10, 40], bryanValue: 10, gap: 0 },
    { code: 'TESTO', name: 'Testosterone Total', shortName: 'Testosterone', value: 580, unit: 'ng/dL', classification: 'OPTIMAL', longevityOptimalRange: [500, 900], labRange: [300, 1000], bryanValue: 941, gap: 0 },
    { code: 'TSH', name: 'Thyroid Stimulating Hormone', shortName: 'TSH', value: 1.8, unit: 'mIU/L', classification: 'OPTIMAL', longevityOptimalRange: [1, 2.5], labRange: [0.4, 4.5], bryanValue: 1.0, gap: 0 },
  ],
  bryanComparison: [
    { marker: 'hsCRP', yourValue: 1.4, bryanValue: 0.1, gap: 1.3, verdict: 'Priority gap' },
    { marker: 'LDL-C', yourValue: 128, bryanValue: 45, gap: 83, verdict: 'Work needed' },
    { marker: 'ApoB', yourValue: 105, bryanValue: 50, gap: 55, verdict: 'Priority gap' },
    { marker: 'HDL', yourValue: 62, bryanValue: 78, gap: 16, verdict: 'Close to Bryan' },
    { marker: 'Triglycerides', yourValue: 88, bryanValue: 44, gap: 44, verdict: 'Work needed' },
    { marker: 'HbA1c', yourValue: 5.4, bryanValue: 4.5, gap: 0.9, verdict: 'Close to Bryan' },
    { marker: 'Vitamin D', yourValue: 42, bryanValue: 67.8, gap: 25.8, verdict: 'Work needed' },
    { marker: 'Omega-3 Index', yourValue: 5.8, bryanValue: 9.98, gap: 4.18, verdict: 'Work needed' },
  ],
  nutrition: {
    dailyCalories: 2400,
    macros: { protein: 165, carbs: 240, fat: 80 },
    proteinPerKg: 2.0,
    eatingWindow: '10:00 - 19:00 (9h window)',
    meals: [],
    mealOptions: {
      breakfast: [
        { name: 'Greek yogurt + berries + walnuts + honey', description: 'Probiotic + polyphenols + omega-3 fats', calories: 480, protein_g: 28, carbs_g: 35, fat_g: 22, fiber_g: 8, sugar_g: 18, sodium_mg: 80, prepMinutes: 3, ingredients: ['Greek yogurt 250g', 'mixed berries 100g', 'walnuts 25g', 'honey 1 tsp'], whyForYou: 'Live cultures support gut microbiome diversity' },
        { name: '3 eggs + smashed avocado on rye', description: 'High-protein anchor, keeps you full until lunch', calories: 520, protein_g: 28, carbs_g: 30, fat_g: 28, fiber_g: 9, sugar_g: 4, sodium_mg: 480, prepMinutes: 8, ingredients: ['3 eggs', '½ avocado', '2 slices rye', 'EVOO 1 tsp'], whyForYou: 'Protein-first anchors blood sugar for the day' },
        { name: 'Overnight oats + chia + banana + almond butter', description: 'Slow carbs + plant omega-3, prep night before', calories: 540, protein_g: 18, carbs_g: 65, fat_g: 22, fiber_g: 14, sugar_g: 16, sodium_mg: 30, prepMinutes: 5, ingredients: ['oats 70g', 'chia 2 tbsp', 'banana ½', 'almond butter 1 tbsp'], whyForYou: 'Beta-glucan in oats lowers LDL — direct hit on your gap' },
      ],
      lunch: [
        { name: 'Wild salmon + sweet potato + dark greens', description: 'Omega-3 EPA/DHA + complex carb + nitrates', calories: 680, protein_g: 42, carbs_g: 60, fat_g: 24, fiber_g: 11, sugar_g: 14, sodium_mg: 380, prepMinutes: 20, ingredients: ['salmon 200g', 'sweet potato 250g', 'kale 120g'], whyForYou: 'Salmon hits Omega-3 Index targets — your 5.8% needs to climb to 8%+' },
        { name: 'Grilled chicken + quinoa + roasted veg', description: 'Lean protein + complete carb + fiber', calories: 720, protein_g: 50, carbs_g: 70, fat_g: 14, fiber_g: 12, sugar_g: 6, sodium_mg: 420, prepMinutes: 25, ingredients: ['chicken breast 200g', 'quinoa 90g dry', 'broccoli 250g'], whyForYou: 'Quinoa is a complete protein and pairs gluten-free' },
        { name: 'Lentil + chickpea power bowl', description: 'Plant protein, fiber, sustained energy', calories: 700, protein_g: 32, carbs_g: 90, fat_g: 16, fiber_g: 22, sugar_g: 10, sodium_mg: 420, prepMinutes: 15, ingredients: ['lentils 90g cooked', 'chickpeas 100g', 'tahini 1 tbsp'], whyForYou: 'Soluble fiber drops LDL — directly targets your apoB issue' },
      ],
      dinner: [
        { name: 'Cod + roasted vegetables', description: 'Light protein, easy on digestion before bed', calories: 580, protein_g: 38, carbs_g: 35, fat_g: 14, fiber_g: 10, sugar_g: 9, sodium_mg: 320, prepMinutes: 20, ingredients: ['cod 220g', 'mixed roasted veg 350g', 'EVOO 1 tbsp'], whyForYou: 'White fish is light, fast-digesting — clean overnight digestion' },
        { name: 'Mediterranean traybake (fish + olives + tomatoes)', description: 'One-pan, nutrient-dense, weeknight-fast', calories: 620, protein_g: 35, carbs_g: 30, fat_g: 28, fiber_g: 8, sugar_g: 10, sodium_mg: 580, prepMinutes: 30, ingredients: ['fish 200g', 'cherry tomatoes 250g', 'olives 60g'], whyForYou: 'Mediterranean pattern has the strongest mortality data' },
        { name: 'Veggie + bean chili (batch-cookable)', description: 'Plant-forward, fiber-rich, satisfying', calories: 560, protein_g: 25, carbs_g: 60, fat_g: 12, fiber_g: 18, sugar_g: 14, sodium_mg: 540, prepMinutes: 35, ingredients: ['kidney + black beans 220g', 'tomato sauce 200g', 'pepper + onion'], whyForYou: 'Make Sunday, eat through the week — easy adherence' },
      ],
      snacks: [
        { name: 'Apple + 2 tbsp almond butter', description: 'Fiber + healthy fat', calories: 250, protein_g: 7, carbs_g: 28, fat_g: 16, fiber_g: 7, sugar_g: 19, sodium_mg: 5, prepMinutes: 1, ingredients: ['apple 1 medium', 'almond butter 2 tbsp'], whyForYou: 'Polyphenols + monounsaturated fat' },
        { name: 'Hummus + raw veg sticks', description: 'Crunch + plant protein + fiber', calories: 200, protein_g: 8, carbs_g: 22, fat_g: 10, fiber_g: 7, sugar_g: 5, sodium_mg: 320, prepMinutes: 3, ingredients: ['hummus 80g', 'mixed raw veg 200g'], whyForYou: 'Chickpea fiber feeds gut bacteria' },
        { name: 'Hard-boiled eggs (2) + cherry tomatoes', description: 'Portable protein anywhere', calories: 180, protein_g: 14, carbs_g: 6, fat_g: 11, fiber_g: 2, sugar_g: 4, sodium_mg: 200, prepMinutes: 1, ingredients: ['2 boiled eggs', 'cherry tomatoes 100g'], whyForYou: 'Choline from yolk supports brain + liver' },
      ],
    },
    dailyMaximums: { sugar_g: 25, sodium_mg: 2000, saturatedFat_g: 18, fiber_g_min: 32, water_ml_min: 2800 },
    generalRecommendations: [
      'Eat protein FIRST at every meal — blunts post-meal glucose spike',
      'Hydrate 500ml on waking before any caffeine',
      'No liquid calories — juice, sweetened coffee, sugary drinks',
      'Last meal 3+ hours before bed',
      'Aim 30g+ protein per meal',
      'Eat the rainbow — 30+ different plants per week',
      'Chew each bite 20+ times',
      '5-min walk after meals — drops glucose ~20%',
    ],
    foodsToAdd: [
      { food: 'Fatty fish (salmon, sardines) 3x/week', why: 'Direct hit on Omega-3 Index 5.8% → target 8%+', frequency: '3x/week' },
      { food: 'Oat bran 30g daily', why: 'Beta-glucan lowers LDL — your priority gap', frequency: 'daily' },
      { food: 'Berries 2 cups daily', why: 'Polyphenols target inflammation (hsCRP 1.4)', frequency: 'daily' },
    ],
    foodsToReduce: [
      { food: 'Processed meats (sausage, bacon)', why: 'Drives hsCRP + ApoB — both already elevated' },
      { food: 'Refined carbs (white bread, pasta)', why: 'Spikes glucose, pushes triglycerides up' },
    ],
    hydrationLiters: 2.8,
  },
  supplements: [
    { name: 'Omega-3 EPA/DHA', dose: '2.5g EPA+DHA combined', timing: 'With dinner', form: 'triglyceride form softgel', withFood: true, howToTake: 'Take with the fattiest meal — boosts EPA/DHA absorption ~2-3×. Refrigerate to prevent oxidation.', alreadyTaking: false, justification: 'Your Omega-3 Index is 5.8% (target >8%). 2.5g/day for 12 weeks should bring you to 7-9%. Reduces hsCRP. Bryan takes 1.3g.', interactions: ['Mild blood-thinning effect — discuss with doctor if on anticoagulants'], monthlyCostRon: 70, priority: 'MUST', emagSearchQuery: 'Omega 3 EPA DHA triglyceride 2g' },
    { name: 'Vitamin D3 + K2-MK7', dose: '4000 IU D3 + 200mcg K2', timing: 'Morning, with breakfast', form: 'softgel', withFood: true, howToTake: 'Swallow with 250ml water + a fatty meal (10g+ fat) — fat-soluble, dry stomach wastes 70%', alreadyTaking: true, justification: 'Your D3 is 42 ng/mL (good), K2 keeps calcium in bones not arteries. Maintenance dose given your level.', interactions: [], monthlyCostRon: 40, priority: 'MUST', emagSearchQuery: 'Vitamin D3 K2 4000 IU' },
    { name: 'Magnesium Glycinate', dose: '400mg elemental', timing: 'Evening, 60 min before bed', form: 'capsule (glycinate, NOT oxide)', withFood: false, howToTake: 'With 250ml water. Glycinate is calming + bioavailable. Avoid oxide — mostly excreted unused.', alreadyTaking: false, justification: '300+ enzymatic reactions. Sleep architecture, stress, recovery.', interactions: ['Take 2h apart from antibiotics'], monthlyCostRon: 30, priority: 'MUST', emagSearchQuery: 'Magnesium glycinate 400mg' },
    { name: 'Curcumin (with piperine)', dose: '1g curcumin + 10mg piperine', timing: 'With largest meal', form: 'capsule', withFood: true, howToTake: 'With a fatty meal — fat-soluble. Piperine boosts bioavailability 20×.', alreadyTaking: false, justification: 'Your hsCRP is 1.4 (target <1). Curcumin reduces inflammation. Stack with omega-3 for compound effect.', interactions: ['Mild blood-thinning — pause 1 week pre-surgery'], monthlyCostRon: 45, priority: 'STRONG', emagSearchQuery: 'Curcumin piperine 1000mg' },
    { name: 'Creatine Monohydrate', dose: '5g daily', timing: 'Anytime — consistency > timing', form: 'micronized powder', withFood: false, howToTake: 'Mix in 250ml water or smoothie. Same time each day to build the habit.', alreadyTaking: false, justification: 'Most-studied supplement. Strength +5-15%, cognition under sleep deprivation, longevity signals.', interactions: [], monthlyCostRon: 25, priority: 'STRONG', emagSearchQuery: 'Creatine monohydrate micronized' },
    { name: 'Berberine', dose: '500mg with 2 largest meals', timing: 'With meals (lunch + dinner)', form: 'capsule', withFood: true, howToTake: 'With largest carb meal. Cycle 8 weeks on, 2 weeks off to prevent gut microbiome adaptation.', alreadyTaking: false, justification: 'Your HbA1c is 5.4 (just-OK). Berberine improves insulin sensitivity ~10-20% — pre-emptive lever for metabolic health.', interactions: ['Reduce dose if on metformin or BP meds'], monthlyCostRon: 55, priority: 'OPTIONAL', emagSearchQuery: 'Berberine 500mg' },
  ],
  supplementsHowTo: [
    'Always swallow with 200ml+ water — never juice or coffee (tannins block absorption)',
    'Fat-soluble vitamins (D3, K2, A, E) need 10g+ fat in the same meal — taking them dry wastes 70%',
    'Magnesium glycinate at NIGHT — calming, supports sleep. Magnesium oxide is mostly excreted unused',
    'Iron and calcium block each other — separate by 2 hours minimum',
    'Coffee blocks iron + zinc absorption — wait 1 hour either side',
    'Don\'t mix all supplements in one shot — split AM (water-soluble), midday (fat-soluble), evening (calming)',
  ],
  exercise: {
    weeklyPlan: [
      { day: 'Monday', activity: 'Upper body strength', exercises: ['Bench press 4×6-8', 'Pull-ups 4×6-10', 'OHP 3×8', 'Barbell row 3×8'], duration: '60 min', intensity: 'Heavy', notes: 'Add 2.5kg or 1 rep weekly' },
      { day: 'Tuesday', activity: 'Zone 2 cardio (bike/row)', exercises: ['Erg bike 45 min @ 130-145 bpm'], duration: '45 min', intensity: 'Zone 2', notes: 'Conversational pace, nasal breathing' },
      { day: 'Wednesday', activity: 'Lower body strength', exercises: ['Back squat 4×6-8', 'RDL 3×8', 'Walking lunge 3×10/leg'], duration: '60 min', intensity: 'Heavy', notes: 'Squat depth at least parallel' },
      { day: 'Thursday', activity: 'Zone 2 cardio', exercises: ['Bike or jog 45 min easy'], duration: '45 min', intensity: 'Zone 2', notes: '' },
      { day: 'Friday', activity: 'Full body + HIIT finisher', exercises: ['Deadlift 3×5', 'Pull-up 3×AMRAP', 'Assault bike 8×30s sprint / 90s easy'], duration: '60 min', intensity: 'High', notes: 'Save HIIT for the end' },
      { day: 'Saturday', activity: 'Long walk/hike outside', exercises: ['90 min hike or brisk walk'], duration: '90 min', intensity: 'Zone 2', notes: 'Sunlight + nature' },
      { day: 'Sunday', activity: 'Active recovery', exercises: ['Sauna 20 min', 'Mobility + yoga 20 min', 'Walk 30 min'], duration: '60 min', intensity: 'Recovery', notes: 'Sauna 20min × 4/wk associated with -40% all-cause mortality' },
    ],
    zone2Target: 180,
    strengthSessions: 3,
    hiitSessions: 1,
    dailyStepsTarget: 10000,
    warmupRoutine: ['5 min easy cardio', 'Hip circles × 10', 'Arm circles × 10', 'Bodyweight squats × 10', 'Shoulder dislocates × 10'],
    cooldownRoutine: ['5 min walk to bring HR down', 'Hamstring stretch 30s/side', 'Hip flexor stretch 30s/side', 'Box breathing 4-4-4-4 × 10'],
    progressionNotes: 'Add 2.5kg or 1 rep weekly on lifts. Bump cardio +5 min/wk until 60 min. Deload week every 6 weeks (-40% volume).',
    gymAccess: 'gym',
    generalRecommendations: [
      'Warm up 5 min before any heavy work — never cold sets',
      'Progressive overload is the core principle — add 2.5kg or 1 rep weekly',
      'Zone 2 = nasal-breathing pace. If mouth-breathing, slow down',
      'Strength BEFORE cardio if same day',
      'Sleep 8h on training days — adaptation happens then, not in the gym',
      'Rest 48h between same muscle group',
      'Track lifts — what gets measured improves',
    ],
  },
  sleep: {
    targetBedtime: '22:30',
    targetWakeTime: '06:30',
    targetDuration: '8h 0m',
    idealBedtime: '22:30',
    idealWakeTime: '06:30',
    windDownRoutine: [
      { time: '-90 min', action: 'Dim all lights to <50% brightness, screens off' },
      { time: '-60 min', action: 'Hot shower (10 min) — body cools after, signals sleep' },
      { time: '-45 min', action: 'Magnesium glycinate 400mg + L-theanine 200mg if stressed' },
      { time: '-30 min', action: 'Read fiction or do box breathing 5 min' },
      { time: '0 min', action: 'Lights out, room cool, phone in another room' },
    ],
    environment: [
      { item: 'Temperature 18-20°C', why: 'Core body temp must drop to fall asleep' },
      { item: 'Total darkness (blackout curtains or sleep mask)', why: 'Even small light suppresses melatonin' },
      { item: 'Quiet or white noise machine', why: 'Random sounds cause unremembered micro-arousals' },
    ],
    bedroomChecklist: [
      { item: 'Blackout curtains OR a quality sleep mask', why: 'Eliminates streetlight bleed; deepens REM' },
      { item: 'Room temperature 18-20°C (64-68°F)', why: 'Cool air helps core body temp drop — required for sleep onset + maintenance' },
      { item: 'No phone in bedroom (or airplane mode + face-down across the room)', why: 'Removes 3 AM scroll temptation; eliminates notifications' },
      { item: 'White noise machine or earplugs if street noise', why: 'Random sounds cause micro-arousals you don\'t remember' },
      { item: 'Bedroom for sleep + sex only', why: 'Trains brain to associate the room with shutdown' },
    ],
    supplementsForSleep: [],
    morningLightMinutes: 15,
    morningRoutine: [
      '15 min direct sunlight (no sunglasses) within 30 min of waking',
      'Hydrate 500ml water with pinch of sea salt + lemon',
      'Box breathing 4-4-4-4 × 5 cycles',
      'Cold splash on face for alertness',
    ],
    caffeineLimit: 'Currently 240mg/day — keep all coffee before 11 AM. Half-life is 5-6h.',
    generalRecommendations: [
      'Same bedtime AND wake time within 30 min — including weekends',
      'No screens 90 min before bed — blue light suppresses melatonin ~50%',
      'No food 3+ hours before bed',
      'No alcohol 4+ hours before bed — collapses deep sleep ~40%',
      'Caffeine cut-off ~10 hours before bed',
      'Get 10-30 min direct sunlight within 1h of waking',
    ],
  },
  universalTips: [],
  dailySchedule: [
    { time: '06:30', activity: 'Wake — 15 min direct sunlight + 500ml water', category: 'wake', duration: '15 min', notes: 'No phone yet. Sets circadian rhythm.' },
    { time: '06:45', activity: 'Vitamin D3 + K2 with breakfast fat', category: 'supplements', duration: '2 min', notes: 'Fat-soluble — needs the breakfast fat to absorb' },
    { time: '07:30', activity: 'Breakfast — protein-forward (≥30g)', category: 'meal', duration: '20 min', notes: 'Anchors blood sugar' },
    { time: '09:00 - 18:00', activity: 'Work', category: 'work', duration: '', notes: 'Stand + walk 5 min every hour', isBlock: true },
    { time: '13:00', activity: 'Lunch — biggest meal of the day', category: 'meal', duration: '30 min', notes: '10 min walk after — drops glucose ~20%' },
    { time: '18:30', activity: 'Strength training session', category: 'exercise', duration: '60 min', notes: 'Warm up 5 min before any heavy work' },
    { time: '20:00', activity: 'Dinner — lighter, lower-carb', category: 'meal', duration: '30 min', notes: '3+ hours before bed' },
    { time: '21:00', activity: 'Wind-down: dim lights, screens off', category: 'wind-down', duration: '60 min', notes: 'Read, stretch, talk' },
    { time: '21:30', activity: 'Magnesium Glycinate 400mg', category: 'supplements', duration: '2 min', notes: '' },
    { time: '22:30', activity: 'Lights out — bed', category: 'sleep', duration: '8h 0m', notes: '18-20°C, total darkness' },
  ],
  tracking: { daily: ['Weight (morning)', 'Sleep hours + score', 'HRV', 'Steps', 'Mood/energy 1-10'], weekly: ['Waist measurement', 'Workout completion'], retestSchedule: [
    { marker: 'hsCRP', weeks: 12, why: 'Currently 1.4, target <1 — retest after 12 weeks of omega-3 + curcumin' },
    { marker: 'ApoB', weeks: 12, why: 'Priority gap — track response to fiber + diet changes' },
    { marker: 'Omega-3 Index', weeks: 12, why: 'Current 5.8, target 8+, dose adjustment may be needed' },
  ] },
  doctorDiscussion: {
    redFlags: [],
    rxSuggestions: ['Discuss low-dose statin if ApoB doesn\'t drop below 90 in 12 weeks'],
    specialistReferrals: ['Cardiologist for ApoB + LDL discussion (preventive)'],
    testsToOrder: ['Lp(a) — one-time, not currently in your panel', 'Coronary calcium score if 40+'],
  },
  painPointSolutions: [
    { problem: 'Afternoon energy dip around 2-3 PM', likelyCause: 'Post-meal glucose spikes + caffeine wearing off', solution: 'Protein-first lunch, walk 10 min after, no refined carbs, hydrate 500ml', supportingBiomarkers: ['GLUC', 'INSULIN'], expectedTimeline: '7-10 days', checkpoints: ['Rate 2-4 PM energy daily'] },
    { problem: '9 hours sitting daily — back tension', likelyCause: 'Hip flexor shortening + weak posterior chain', solution: 'Hourly stand-walk, hip flexor stretch 2x/day, deadlifts 1x/week', supportingBiomarkers: [], expectedTimeline: '2-3 weeks', checkpoints: ['Morning stiffness 1-10'] },
  ],
  flexRules: [
    { scenario: 'Restaurant dinner', strategy: 'Check menu in advance. Vegetable starter first. Ask sauces on side. Skip bread. One bite of dessert.' },
    { scenario: 'Drinks with friends', strategy: '1 water between drinks. Eat first. Cap at 2. NAC 600mg + B-complex before bed. Skip sugary mixers.' },
    { scenario: 'Travel days', strategy: 'Pre-pack water + protein bar + electrolytes. Walk every 1-2h on flights. 10 min sunlight on landing. Supplements in pill organizer.' },
    { scenario: 'High-stress work week', strategy: 'Sleep 7.5+ h, protein each meal, 20 min walk even if no gym. Drop HIIT — Zone 2 only. Extra magnesium. Box breathing 5 min every 2h.' },
  ],
  weekByWeekPlan: [],
  doctorQuestions: [
    'Can we order an Lp(a) test? It\'s a one-time genetic marker, not in my current panel.',
    'My ApoB is 105 — at what threshold would you discuss a low-dose statin given my hsCRP is also borderline?',
    'I\'d like to add a coronary calcium score for my next physical — what age would you recommend?',
  ],
  roadmap: [
    { week: 'Weeks 1-4', title: 'Foundation', actions: ['Add omega-3 2.5g/day', 'Add 30 min Z2 cardio Tue/Thu', 'Hourly walking break alarm', 'Track hsCRP at 12 weeks'] },
    { week: 'Weeks 5-8', title: 'Build', actions: ['Add curcumin 1g/day with dinner', 'Berberine 500mg with 2 largest meals', 'Bump strength to 3x/week', 'Sleep tracking baseline'] },
    { week: 'Weeks 9-12', title: 'Retest + adjust', actions: ['Full lipid panel + hsCRP + Omega-3 Index', 'Adjust supplement doses based on results', 'If ApoB still >90, statin discussion'] },
  ],
  shoppingList: [
    { category: 'Supplements (monthly)', items: [
      { name: 'Omega-3 EPA/DHA 2g', estimatedCostRon: 70, where: 'eMAG', emagQuery: 'Omega 3 EPA DHA triglyceride', priority: 'buy now' },
      { name: 'Magnesium Glycinate 400mg', estimatedCostRon: 30, where: 'eMAG', emagQuery: 'Magnesium glycinate 400mg', priority: 'buy now' },
      { name: 'Curcumin + piperine', estimatedCostRon: 45, where: 'eMAG', emagQuery: 'Curcumin piperine 1000mg', priority: 'buy now' },
      { name: 'Vitamin D3 + K2', estimatedCostRon: 40, where: 'eMAG', emagQuery: 'Vitamin D3 K2 4000 IU', priority: 'buy now' },
      { name: 'Creatine monohydrate', estimatedCostRon: 25, where: 'eMAG', emagQuery: 'Creatine micronized', priority: 'buy now' },
    ]},
  ],
  costBreakdown: { monthlySupplements: 210, monthlyFood: 800, oneTimeEquipment: 0, quarterlyTesting: 350, totalMonthlyOngoing: 1010, currency: 'RON' },
};
