-- DEPRECATED: contents merged into upgrade.sql and setup-db.sql.
-- Run `upgrade.sql` instead — it's idempotent and covers share_links and
-- compliance_logs plus everything else needed for the current app version.
